/**
 * The Defence Industry Development Grant recipients, announced late July 2026
 * and parsed from the official PDF: 59 companies, 67 grants.
 *
 * This lives in TypeScript rather than a SQL migration on purpose. The purpose
 * strings carry commas, semicolons and full stops, and pasting 30 KB of string
 * literals into the Supabase SQL editor proved unreliable. Importing through the
 * app means the data is typechecked, the insert is parameterised, and no
 * escaping is involved at all.
 *
 * The grant purpose is the load-bearing field: it is the public sentence saying
 * exactly what each company was funded to build, stored verbatim.
 */

export interface SeedOrg {
  legal_name: string;
  state: string;
  tier: string;
  grant_total_aud: number;
  grant_count: number;
  grant_streams: string[];
  new_capability: boolean;
  headline_purpose: string;
}

export interface SeedGrant {
  company: string;
  amount: number;
  stream: string;
  purpose: string;
}

export const SEED_ORGS: SeedOrg[] = [
  { legal_name: "KBE Pty Ltd", state: "NSW", tier: "A", grant_total_aud: 1250000, grant_count: 2, grant_streams: ["Exports", "Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis CNC machine to upscale component manufacture for the Ghost Shark platform" },
  { legal_name: "Cop-A-Mate Products Pty Ltd", state: "Vic", tier: "A", grant_total_aud: 1089278, grant_count: 2, grant_streams: ["Security", "Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure capital equipment to establish local manufacturing capability for mission-critical land-vehicle armour and exhaust components and supporting continuous land-vehicle production and sustainment priorities" },
  { legal_name: "NH Micro Pty Ltd", state: "NSW", tier: "A", grant_total_aud: 1059779, grant_count: 2, grant_streams: ["Exports", "Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure an advanced 5-axis ultra-precision machining platform to establish a scalable ultra-precision manufacturing environment to enable domestic production of mission-critical ballscrew components for control actuation systems used in guided weapons platforms" },
  { legal_name: "SouthernLaunch.Space Pty Ltd", state: "SA", tier: "A", grant_total_aud: 1035600, grant_count: 2, grant_streams: ["Security", "Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire range safety equipment, including communication equipment and range network equipment to support test and evaluation activities" },
  { legal_name: "Aurora Labs Ltd", state: "WA", tier: "A", grant_total_aud: 1000000, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire an advanced laser powder bed fusion machine for the manufacture of propulsion systems in support of multiple capability domains" },
  { legal_name: "Ferra Engineering Pty Ltd", state: "Qld", tier: "A", grant_total_aud: 1000000, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis computer numerical control (CNC) horizontal machining capability to support manufacturing supply into multiple guided weapons and explosive ordnance systems" },
  { legal_name: "Lintek Pty. Limited", state: "NSW", tier: "A", grant_total_aud: 1000000, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a tack bonder, lamination press, deburrer and CNC router to upgrade printed circuit board production facility in support of multiple capability domains" },
  { legal_name: "Micron Manufacturing Pty. Ltd", state: "NSW", tier: "A", grant_total_aud: 1000000, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a machining centre, tooling and associated software for the machining of advanced underwater vehicle super-structures" },
  { legal_name: "Rivierra Pty Ltd", state: "Vic", tier: "A", grant_total_aud: 1000000, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a fully integrated coating line to internalise the powder coating and wet painting of key components manufactured for land systems" },
  { legal_name: "Prism Defence Pty Ltd", state: "SA", tier: "A", grant_total_aud: 935186, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure an excavator to establish a ship motion emulation facility for the test and evaluation of uncrewed aerial systems intended to operate from ships" },
  { legal_name: "NDE Solutions Pty Ltd", state: "SA", tier: "A", grant_total_aud: 916052, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire non-destructive testing equipment to expand local capability in support of continuous naval shipbuilding and sustainment." },
  { legal_name: "Century Engineering Pty Ltd", state: "SA", tier: "A", grant_total_aud: 901557, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure a large-format CNC milling machine for high-precision machining of complex and oversized components within the stringent tolerances and material requirements associated with defence-grade components for naval and land platforms" },
  { legal_name: "Tynbell Sheetmetal Pty Ltd", state: "SA", tier: "A", grant_total_aud: 871173, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire an upgraded laser cutting system to strengthen manufacturing capability in the naval and land domains" },
  { legal_name: "Kennewell Pty Ltd", state: "SA", tier: "A", grant_total_aud: 747754, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis machining centre, vertical lift storage unit and associated equipment for manufacturing supply into infantry fighting vehicle platforms" },
  { legal_name: "Able Industries Engineering Pty Ltd", state: "Vic", tier: "A", grant_total_aud: 715855, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire robotic welding equipment, coordinate measuring machine, CNC router and power supply upgrades to enhance manufacturing capacity for land combat vehicle and continuous naval shipbuilding and sustainment programs" },
  { legal_name: "Verseng Group Pty Ltd", state: "SA", tier: "A", grant_total_aud: 651187, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure robotic welding and autonomous grinding equipment to improve finishing quality and safety in the local production of defence Ground Support Equipment used in sustainment activities, including aircraft sustainment and shipbuilding programs" },
  { legal_name: "Gurit Australia Pty Limited", state: "Qld", tier: "A", grant_total_aud: 559852, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "establish local manufacturing capability for bespoke subsea buoyancy for the Ghost Shark autonomous underwater vehicle" },
  { legal_name: "B. B. Engineering Pty Ltd", state: "Vic", tier: "A", grant_total_aud: 551390, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis CNC machine to enhance component manufacture in support of continuous naval shipbuilding and sustainment programs" },
  { legal_name: "Wessand Pty Ltd", state: "Vic", tier: "A", grant_total_aud: 411189, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire automated garment manufacturing equipment to strengthen domestic combat uniform manufacture" },
  { legal_name: "Land Air Sea Space Pty Ltd", state: "NSW", tier: "B", grant_total_aud: 382000, grant_count: 2, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure and integrate an automated inventory management system to enhance efficiency and scalability, ensuring timely delivery of cable assemblies for land, naval and guided weapons programs" },
  { legal_name: "Dent Engineering Pty Ltd", state: "SA", tier: "B", grant_total_aud: 344722, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a CNC machining centre and lathe for the manufacture of precision components for uncrewed aerial system platforms" },
  { legal_name: "Protonautics Pty Ltd", state: "Qld", tier: "B", grant_total_aud: 323877, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a high-capacity horizontal CNC machine to support the manufacture of precision components for the Redback Infantry Fighting Vehicles." },
  { legal_name: "Value Heat Treatment Pty Ltd", state: "Vic", tier: "B", grant_total_aud: 271262, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "purchase capital equipment to uplift the heat treatment capability for defence components across land, sea, and air platforms" },
  { legal_name: "Prestige Precision Tools Pty Ltd", state: "Qld", tier: "B", grant_total_aud: 250000, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "establish the manufacturing capability of high-performance carbide tools, delivering tooling solutions that meet the stringent requirements of platforms such as the Joint Strike Fighter and other advanced weapons systems" },
  { legal_name: "Skyborne Technologies Pty Ltd", state: "Qld", tier: "B", grant_total_aud: 250000, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "procure a CNC lathe and two automated electronic and avionics testing systems to support the development and integration of autonomous systems" },
  { legal_name: "Specialised Solutions Pty Ltd", state: "SA", tier: "B", grant_total_aud: 243450, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a robotic welding cell and a 10-tonne overhead crane to manufacture high-precision welded components for small and larger modular assemblies used in naval, land and autonomous systems" },
  { legal_name: "Process Rubber & Plastics Pty. Ltd", state: "SA", tier: "B", grant_total_aud: 215829, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis machining centre to increase manufacturing capability for multiple capability domains" },
  { legal_name: "Coastal Aviation Pty Ltd", state: "Qld", tier: "B", grant_total_aud: 198605, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a 5-axis CNC milling machine and fabrication equipment to enhance manufacturing of large defence components for air and guided-weapons platforms" },
  { legal_name: "Jehbco Manufacturing Pty Ltd", state: "NSW", tier: "B", grant_total_aud: 192264, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "purchase a silicone rubber extruder to increase production capacity, improve dimensional accuracy, and enable the manufacture of high-performance silicone profiles for defence sealing and insulation applications across multiple platforms" },
  { legal_name: "Rosebank Engineering Pty Ltd", state: "Vic", tier: "B", grant_total_aud: 185897, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure and integrate a purpose-built cold spray facility with advanced robotic control to support the manufacture of the landing gear for the MQ-28 Ghost Bat" },
  { legal_name: "Currawong Engineering Pty Ltd", state: "Tas", tier: "B", grant_total_aud: 184659, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "procure a vertical machining centre to enhance the manufacture of aerospace-grade electronic speed controllers and engines to support the growing demand from export supply chains" },
  { legal_name: "Luminact Pty Ltd", state: "Vic", tier: "B", grant_total_aud: 142818, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "acquire equipment and commission a transportable Command, Control, Communications, and Computers (C4) Systems Integration Lab to integrate and verify communications, networking, and battlespace management systems, to support repeatable testing and evaluation for land platforms" },
  { legal_name: "Micca Holdings Pty Ltd", state: "NT", tier: "B", grant_total_aud: 112419, grant_count: 2, grant_streams: ["Skilling", "Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a rotary fibre laser cutting machine and a laser welding machine to uplift naval sustainment capability in Northern Australia." },
  { legal_name: "Stahl Metall Pty Ltd", state: "Vic", tier: "B", grant_total_aud: 112272, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "procure automated machinery and quality control equipment to support export opportunities establishing automated wire processing for high performance electrical assemblies used within multiple defence platforms" },
  { legal_name: "Rheon Systems Pty Ltd", state: "Qld", tier: "C", grant_total_aud: 90402, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "procure capital equipment to establish NATA-accredited pressure testing and calibration capability to support test, evaluation and certification activities of Defence systems" },
  { legal_name: "Electronic & Electrical Solutions Pty Ltd", state: "Qld", tier: "C", grant_total_aud: 73115, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire capital equipment to enhance the capacity and quality of manufacturing PCBs used across multiple defence platforms, particularly for guided-weapons production and the sustainment and enhancement of combined-arms land systems" },
  { legal_name: "Amtech Precision Pty Ltd", state: "ACT", tier: "C", grant_total_aud: 69750, grant_count: 1, grant_streams: ["Sovereign Industrial Priorities"], new_capability: true, headline_purpose: "acquire a coordinate measuring machine and profile projector to enhance precision machining manufacturing capability in support of multiple capability domains" },
  { legal_name: "Ron Allum Deepsea Services Pty Ltd", state: "NSW", tier: "C", grant_total_aud: 57634, grant_count: 2, grant_streams: ["Exports", "Skilling"], new_capability: true, headline_purpose: "upgrade its subsea test and evaluation system to support safe, repeatable, and production-scale testing of subsea systems; and obtain relevant ISO certification to remove export barriers" },
  { legal_name: "Arlula Pty Ltd", state: "NSW", tier: "C", grant_total_aud: 56014, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "achieve ISO27001, ISO 9001, and general data protection regulation certification to enable the secure handling of satellite data and overcome existing export barriers to access defence markets in US and Europe" },
  { legal_name: "Blueroom Simulations Pty Ltd", state: "Vic", tier: "C", grant_total_aud: 45800, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "upgrade its mixed reality testing laboratory to allow personnel to develop complex skills through immersive and realistic virtual training environments and to leverage export opportunities" },
  { legal_name: "U-Neek Bending Co. Pty Ltd", state: "Vic", tier: "C", grant_total_aud: 34526, grant_count: 1, grant_streams: ["Exports"], new_capability: true, headline_purpose: "obtain NADCAP certification and acquire advanced welding equipment to enhance the manufacture of critical welded components to support supply chains across aerospace, land and maritime domains." },
  { legal_name: "Thrust Maritime Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 240116, grant_count: 1, grant_streams: ["Skilling"], new_capability: false, headline_purpose: "upskill its workforce in multiple technical and trade disciplines to ensure compliance with RAN and international standards" },
  { legal_name: "JFD Australia Pty Ltd", state: "WA", tier: "D", grant_total_aud: 200000, grant_count: 2, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift governance, physical and cybersecurity posture to meet Defence security requirements" },
  { legal_name: "PHM Technology Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 100000, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift cybersecurity controls and enhance physical security to meet Defence security requirements" },
  { legal_name: "Redarc Defence & Space Pty Ltd", state: "SA", tier: "D", grant_total_aud: 100000, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift physical security to meet Defence security requirements" },
  { legal_name: "HIFraser Pty Ltd", state: "NSW", tier: "D", grant_total_aud: 91294, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift physical security to meet Defence security requirements" },
  { legal_name: "Lunar Outpost Oceania Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 85990, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "enhance Essential Eight security controls and uplift physical security to meet Defence security requirements" },
  { legal_name: "Ascent Professional Services Pty Ltd", state: "SA", tier: "D", grant_total_aud: 84419, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "enhance cybersecurity maturity in order to meet Defence Security requirements" },
  { legal_name: "APV Engineering and Testing Services Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 83746, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { legal_name: "Automation and Process Control Services Pty Ltd", state: "SA", tier: "D", grant_total_aud: 51250, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { legal_name: "Switchmode Power Supplies Pty Ltd", state: "NSW", tier: "D", grant_total_aud: 38864, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift security controls to meet Defence security requirements" },
  { legal_name: "Bastion Defence Consulting Pty Ltd", state: "SA", tier: "D", grant_total_aud: 34550, grant_count: 1, grant_streams: ["Skilling"], new_capability: false, headline_purpose: "upskill engineering personnel in model-based architectural design, requirements management, and virtual verification and validation" },
  { legal_name: "Applied Virtual Simulation Pty Ltd", state: "NSW", tier: "D", grant_total_aud: 32623, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift physical security to meet Defence security requirements" },
  { legal_name: "AST Oceanics Pty Ltd", state: "WA", tier: "D", grant_total_aud: 28367, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { legal_name: "Mellori Solutions Pty Ltd", state: "NSW", tier: "D", grant_total_aud: 24968, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift physical security to meet Defence security requirements" },
  { legal_name: "Hargo Engineering Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 20000, grant_count: 1, grant_streams: ["Skilling"], new_capability: false, headline_purpose: "upskill staff through on-the-job training of apprentices leading to a Certificate III in Engineering - Mechanical Trade" },
  { legal_name: "Consunet Pty Ltd", state: "SA", tier: "D", grant_total_aud: 16346, grant_count: 1, grant_streams: ["Security"], new_capability: false, headline_purpose: "uplift cybersecurity controls to meet Defence security requirements." },
  { legal_name: "Huber & Suhner (Australia) Pty Ltd", state: "NSW", tier: "D", grant_total_aud: 6572, grant_count: 1, grant_streams: ["Skilling"], new_capability: false, headline_purpose: "develop staff through on-the-job training in cable and harness manufacturing and inspection" },
  { legal_name: "SYPAQ Systems Pty Ltd", state: "Vic", tier: "D", grant_total_aud: 6315, grant_count: 1, grant_streams: ["Skilling"], new_capability: false, headline_purpose: "develop workforce capability in electronic warfare" },
];

export const SEED_GRANTS: SeedGrant[] = [
  { company: "Aurora Labs Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire an advanced laser powder bed fusion machine for the manufacture of propulsion systems in support of multiple capability domains" },
  { company: "Cop-A-Mate Products Pty Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "procure capital equipment to establish local manufacturing capability for mission-critical land-vehicle armour and exhaust components and supporting continuous land-vehicle production and sustainment priorities" },
  { company: "Ferra Engineering Pty Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis computer numerical control (CNC) horizontal machining capability to support manufacturing supply into multiple guided weapons and explosive ordnance systems" },
  { company: "KBE Pty Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis CNC machine to upscale component manufacture for the Ghost Shark platform" },
  { company: "Lintek Pty. Limited", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire a tack bonder, lamination press, deburrer and CNC router to upgrade printed circuit board production facility in support of multiple capability domains" },
  { company: "Micron Manufacturing Pty. Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire a machining centre, tooling and associated software for the machining of advanced underwater vehicle super-structures" },
  { company: "Rivierra Pty Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire a fully integrated coating line to internalise the powder coating and wet painting of key components manufactured for land systems" },
  { company: "SouthernLaunch.Space Pty Ltd", amount: 1000000, stream: "Sovereign Industrial Priorities", purpose: "acquire range safety equipment, including communication equipment and range network equipment to support test and evaluation activities" },
  { company: "Prism Defence Pty Ltd", amount: 935186, stream: "Sovereign Industrial Priorities", purpose: "procure an excavator to establish a ship motion emulation facility for the test and evaluation of uncrewed aerial systems intended to operate from ships" },
  { company: "NDE Solutions Pty Ltd", amount: 916052, stream: "Sovereign Industrial Priorities", purpose: "acquire non-destructive testing equipment to expand local capability in support of continuous naval shipbuilding and sustainment." },
  { company: "Century Engineering Pty Ltd", amount: 901557, stream: "Sovereign Industrial Priorities", purpose: "procure a large-format CNC milling machine for high-precision machining of complex and oversized components within the stringent tolerances and material requirements associated with defence-grade components for naval and land platforms" },
  { company: "Tynbell Sheetmetal Pty Ltd", amount: 871173, stream: "Sovereign Industrial Priorities", purpose: "acquire an upgraded laser cutting system to strengthen manufacturing capability in the naval and land domains" },
  { company: "NH Micro Pty Ltd", amount: 824779, stream: "Sovereign Industrial Priorities", purpose: "procure an advanced 5-axis ultra-precision machining platform to establish a scalable ultra-precision manufacturing environment to enable domestic production of mission-critical ballscrew components for control actuation systems used in guided weapons platforms" },
  { company: "Kennewell Pty Ltd", amount: 747754, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis machining centre, vertical lift storage unit and associated equipment for manufacturing supply into infantry fighting vehicle platforms" },
  { company: "Able Industries Engineering Pty Ltd", amount: 715855, stream: "Sovereign Industrial Priorities", purpose: "acquire robotic welding equipment, coordinate measuring machine, CNC router and power supply upgrades to enhance manufacturing capacity for land combat vehicle and continuous naval shipbuilding and sustainment programs" },
  { company: "Verseng Group Pty Ltd", amount: 651187, stream: "Sovereign Industrial Priorities", purpose: "procure robotic welding and autonomous grinding equipment to improve finishing quality and safety in the local production of defence Ground Support Equipment used in sustainment activities, including aircraft sustainment and shipbuilding programs" },
  { company: "Gurit Australia Pty Limited", amount: 559852, stream: "Sovereign Industrial Priorities", purpose: "establish local manufacturing capability for bespoke subsea buoyancy for the Ghost Shark autonomous underwater vehicle" },
  { company: "B. B. Engineering Pty Ltd", amount: 551390, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis CNC machine to enhance component manufacture in support of continuous naval shipbuilding and sustainment programs" },
  { company: "Wessand Pty Ltd", amount: 411189, stream: "Sovereign Industrial Priorities", purpose: "acquire automated garment manufacturing equipment to strengthen domestic combat uniform manufacture" },
  { company: "Dent Engineering Pty Ltd", amount: 344722, stream: "Sovereign Industrial Priorities", purpose: "acquire a CNC machining centre and lathe for the manufacture of precision components for uncrewed aerial system platforms" },
  { company: "Protonautics Pty Ltd", amount: 323877, stream: "Sovereign Industrial Priorities", purpose: "acquire a high-capacity horizontal CNC machine to support the manufacture of precision components for the Redback Infantry Fighting Vehicles." },
  { company: "Value Heat Treatment Pty Ltd", amount: 271262, stream: "Sovereign Industrial Priorities", purpose: "purchase capital equipment to uplift the heat treatment capability for defence components across land, sea, and air platforms" },
  { company: "KBE Pty Ltd", amount: 250000, stream: "Exports", purpose: "procure automated machinery to expand its advanced manufacturing capability and achieve AS9100D certification to support defence and aerospace export supply chains" },
  { company: "Prestige Precision Tools Pty Ltd", amount: 250000, stream: "Exports", purpose: "establish the manufacturing capability of high-performance carbide tools, delivering tooling solutions that meet the stringent requirements of platforms such as the Joint Strike Fighter and other advanced weapons systems" },
  { company: "Skyborne Technologies Pty Ltd", amount: 250000, stream: "Exports", purpose: "procure a CNC lathe and two automated electronic and avionics testing systems to support the development and integration of autonomous systems" },
  { company: "Specialised Solutions Pty Ltd", amount: 243450, stream: "Sovereign Industrial Priorities", purpose: "acquire a robotic welding cell and a 10-tonne overhead crane to manufacture high-precision welded components for small and larger modular assemblies used in naval, land and autonomous systems" },
  { company: "Thrust Maritime Pty Ltd", amount: 240116, stream: "Skilling", purpose: "upskill its workforce in multiple technical and trade disciplines to ensure compliance with RAN and international standards" },
  { company: "NH Micro Pty Ltd", amount: 235000, stream: "Exports", purpose: "procure an ultra-precision coordinate measuring machine to scale up the production and export of critical Control Actuation System and in-space propulsion components to support guided weapons programs" },
  { company: "Process Rubber & Plastics Pty. Ltd", amount: 215829, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis machining centre to increase manufacturing capability for multiple capability domains" },
  { company: "Land Air Sea Space Pty Ltd", amount: 212652, stream: "Sovereign Industrial Priorities", purpose: "procure and integrate an automated inventory management system to enhance efficiency and scalability, ensuring timely delivery of cable assemblies for land, naval and guided weapons programs" },
  { company: "Coastal Aviation Pty Ltd", amount: 198605, stream: "Sovereign Industrial Priorities", purpose: "acquire a 5-axis CNC milling machine and fabrication equipment to enhance manufacturing of large defence components for air and guided-weapons platforms" },
  { company: "Jehbco Manufacturing Pty Ltd", amount: 192264, stream: "Sovereign Industrial Priorities", purpose: "purchase a silicone rubber extruder to increase production capacity, improve dimensional accuracy, and enable the manufacture of high-performance silicone profiles for defence sealing and insulation applications across multiple platforms" },
  { company: "Rosebank Engineering Pty Ltd", amount: 185897, stream: "Sovereign Industrial Priorities", purpose: "procure and integrate a purpose-built cold spray facility with advanced robotic control to support the manufacture of the landing gear for the MQ-28 Ghost Bat" },
  { company: "Currawong Engineering Pty Ltd", amount: 184659, stream: "Exports", purpose: "procure a vertical machining centre to enhance the manufacture of aerospace-grade electronic speed controllers and engines to support the growing demand from export supply chains" },
  { company: "Land Air Sea Space Pty Ltd", amount: 169348, stream: "Sovereign Industrial Priorities", purpose: "acquire electric stripping machines, cutting and crimping tools, and associated equipment to expand production capacity for supply into various land and naval platforms" },
  { company: "Luminact Pty Ltd", amount: 142818, stream: "Exports", purpose: "acquire equipment and commission a transportable Command, Control, Communications, and Computers (C4) Systems Integration Lab to integrate and verify communications, networking, and battlespace management systems, to support repeatable testing and evaluation for land platforms" },
  { company: "Stahl Metall Pty Ltd", amount: 112272, stream: "Exports", purpose: "procure automated machinery and quality control equipment to support export opportunities establishing automated wire processing for high performance electrical assemblies used within multiple defence platforms" },
  { company: "JFD Australia Pty Ltd", amount: 100000, stream: "Security", purpose: "uplift governance, physical and cybersecurity posture to meet Defence security requirements" },
  { company: "JFD Australia Pty Ltd", amount: 100000, stream: "Security", purpose: "uplift physical security to meet Defence security requirements" },
  { company: "PHM Technology Pty Ltd", amount: 100000, stream: "Security", purpose: "uplift cybersecurity controls and enhance physical security to meet Defence security requirements" },
  { company: "Redarc Defence & Space Pty Ltd", amount: 100000, stream: "Security", purpose: "uplift physical security to meet Defence security requirements" },
  { company: "HIFraser Pty Ltd", amount: 91294, stream: "Security", purpose: "uplift physical security to meet Defence security requirements" },
  { company: "Rheon Systems Pty Ltd", amount: 90402, stream: "Sovereign Industrial Priorities", purpose: "procure capital equipment to establish NATA-accredited pressure testing and calibration capability to support test, evaluation and certification activities of Defence systems" },
  { company: "Cop-A-Mate Products Pty Ltd", amount: 89278, stream: "Security", purpose: "uplift physical and ICT security to meet Defence security requirements" },
  { company: "Lunar Outpost Oceania Pty Ltd", amount: 85990, stream: "Security", purpose: "enhance Essential Eight security controls and uplift physical security to meet Defence security requirements" },
  { company: "Ascent Professional Services Pty Ltd", amount: 84419, stream: "Security", purpose: "enhance cybersecurity maturity in order to meet Defence Security requirements" },
  { company: "APV Engineering and Testing Services Pty Ltd", amount: 83746, stream: "Security", purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { company: "Electronic & Electrical Solutions Pty Ltd", amount: 73115, stream: "Sovereign Industrial Priorities", purpose: "acquire capital equipment to enhance the capacity and quality of manufacturing PCBs used across multiple defence platforms, particularly for guided-weapons production and the sustainment and enhancement of combined-arms land systems" },
  { company: "Amtech Precision Pty Ltd", amount: 69750, stream: "Sovereign Industrial Priorities", purpose: "acquire a coordinate measuring machine and profile projector to enhance precision machining manufacturing capability in support of multiple capability domains" },
  { company: "Micca Holdings Pty Ltd", amount: 62419, stream: "Sovereign Industrial Priorities", purpose: "acquire a rotary fibre laser cutting machine and a laser welding machine to uplift naval sustainment capability in Northern Australia." },
  { company: "Arlula Pty Ltd", amount: 56014, stream: "Exports", purpose: "achieve ISO27001, ISO 9001, and general data protection regulation certification to enable the secure handling of satellite data and overcome existing export barriers to access defence markets in US and Europe" },
  { company: "Ron Allum Deepsea Services Pty Ltd", amount: 51609, stream: "Exports", purpose: "upgrade its subsea test and evaluation system to support safe, repeatable, and production-scale testing of subsea systems; and obtain relevant ISO certification to remove export barriers" },
  { company: "Automation and Process Control Services Pty Ltd", amount: 51250, stream: "Security", purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { company: "Micca Holdings Pty Ltd", amount: 50000, stream: "Skilling", purpose: "upskill staff through on-the-job training and the supervision of apprentices to support naval maintenance activities" },
  { company: "Blueroom Simulations Pty Ltd", amount: 45800, stream: "Exports", purpose: "upgrade its mixed reality testing laboratory to allow personnel to develop complex skills through immersive and realistic virtual training environments and to leverage export opportunities" },
  { company: "Switchmode Power Supplies Pty Ltd", amount: 38864, stream: "Security", purpose: "uplift security controls to meet Defence security requirements" },
  { company: "SouthernLaunch.Space Pty Ltd", amount: 35600, stream: "Security", purpose: "enhance Essential Eight security controls to meet Defence security requirements" },
  { company: "Bastion Defence Consulting Pty Ltd", amount: 34550, stream: "Skilling", purpose: "upskill engineering personnel in model-based architectural design, requirements management, and virtual verification and validation" },
  { company: "U-Neek Bending Co. Pty Ltd", amount: 34526, stream: "Exports", purpose: "obtain NADCAP certification and acquire advanced welding equipment to enhance the manufacture of critical welded components to support supply chains across aerospace, land and maritime domains." },
  { company: "Applied Virtual Simulation Pty Ltd", amount: 32623, stream: "Security", purpose: "uplift physical security to meet Defence security requirements" },
  { company: "AST Oceanics Pty Ltd", amount: 28367, stream: "Security", purpose: "uplift cybersecurity controls to meet Defence security requirements" },
  { company: "Mellori Solutions Pty Ltd", amount: 24968, stream: "Security", purpose: "uplift physical security to meet Defence security requirements" },
  { company: "Hargo Engineering Pty Ltd", amount: 20000, stream: "Skilling", purpose: "upskill staff through on-the-job training of apprentices leading to a Certificate III in Engineering - Mechanical Trade" },
  { company: "Consunet Pty Ltd", amount: 16346, stream: "Security", purpose: "uplift cybersecurity controls to meet Defence security requirements." },
  { company: "Huber & Suhner (Australia) Pty Ltd", amount: 6572, stream: "Skilling", purpose: "develop staff through on-the-job training in cable and harness manufacturing and inspection" },
  { company: "SYPAQ Systems Pty Ltd", amount: 6315, stream: "Skilling", purpose: "develop workforce capability in electronic warfare" },
  { company: "Ron Allum Deepsea Services Pty Ltd", amount: 6025, stream: "Skilling", purpose: "upskill technical personnel in software coding and systems engineering to enhance in-house design and production capabilities for defence projects" },
];
