/**
 * The Ironpeak pipeline as handed over on 7 August 2026.
 *
 * This REPLACES every earlier dataset. The previous files held 76 records of
 * which 51 were triaged out; those are gone deliberately and must not be
 * resurrected. Thirty companies, nothing else.
 *
 * TypeScript rather than SQL because 30 KB of string literals proved
 * unreliable to paste into the Supabase editor: semicolons inside prose kept
 * being read as statement terminators. It imports in-app instead.
 *
 * Send times are never on the hour or the half hour. That is Kyle's rule so
 * mail reads as hand-sent, and it is preserved verbatim from the handoff
 * rather than regenerated. WA sends are stored in AEST and land mid-morning
 * Perth.
 */

export type PipelineStage =
  | "contacted"
  | "queued"
  | "blocked"
  | "linkedin_only";

export interface PipelineRecord {
  rank: number;
  tier: 1 | 2 | 3;
  company: string;
  tradingName?: string;
  channel: "DIDG" | "AIC";
  stage: PipelineStage;
  state: string;
  /** "NO WEBSITE" is a valid and important value. */
  domain: string;
  email: string;
  emailSourceNote: string;
  contactName: string;
  contactTitle?: string;
  nameVerified: "own-site" | "directory" | "unverified";
  sentDate?: string;
  followupDue?: string;
  /** When to send. Absent for contacted, blocked and linkedin-only records. */
  scheduledSendAt?: string;
  hook: string;
  /** The date the hook was checked against the live site. */
  hookVerified: string;
  /** True where the hook is late-July research that has NOT been re-checked. */
  staleHook?: boolean;
  fallbackGreeting?: string;
  /** Shown as an undismissable warning on the record. */
  hardWarning?: string;
  notes: string;
}

export const PIPELINE_V2: PipelineRecord[] = [
  {
    rank: 1,
    tier: 1,
    company: "Coastal Aviation Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Tas",
    domain: "coastalaviation.com.au",
    email: "info@coastalaviation.com.au",
    emailSourceNote: "contact page",
    contactName: "Robert Stowe",
    nameVerified: "directory",
    sentDate: "2026-08-05",
    followupDue: "2026-08-13",
    hook: "Their website is compromised and serving pharmacy spam on WordPress 4.8.25.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "FOLLOW UP IMMEDIATELY. Do not wait for the day 8 to 10 window.\n\nHomepage runs WordPress 4.8.25, released around 2017. In the VISIBLE text, directly beneath their legitimate Part 145 paragraph: viagra x3, cialis x3, phenq x1, farmacia x3, with seven live outbound links to euro2000.org, mifarmacia24.com, farmaciaespana247.com and sportzfuel.com. A broken shortcode [products columns=6 paginate=true limit=6] also prints raw on the page.\n\nWhy rank 1: the only true painkiller in the pipeline. It is damaging them right now, they can verify it in ten seconds, and telling them is a favour whether or not it produces work. The email carries no pitch. Any competent WordPress developer can clean it, saying so costs nothing, and it makes a reply near certain. The conversation that follows, who should be looking after this, is the one worth having.",
  },
  {
    rank: 2,
    tier: 1,
    company: "B.B. Engineering Pty Ltd",
    channel: "DIDG",
    stage: "queued",
    state: "Vic",
    domain: "bbengineering.com.au",
    email: "sales@bbengineering.com.au",
    emailSourceNote: "footer and contact page",
    contactName: "Gary Busuttil",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-10T08:47:00+10:00",
    hook: "Their JOSCAR-AU certificate, displayed on their own homepage, shows Renewal Date 11 August 2026.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "TIME CRITICAL. If this does not go Monday morning the hook is gone.\n\nJOSCAR-AU-Cert.jpg was downloaded from their homepage and read directly rather than trusting an agent summary. It reads Renewal Date: 11 August 2026 beneath Colin Maund, CEO, Hellios Information. That is Tuesday. After it passes, the certificate a prime sees on their site is out of date.\n\nHand-built PHP on Apache, no CMS, so no incumbent agency. Copyright 2026 is current, so they do maintain it. Only two PDFs, both certificates, and no capability statement, so the certificates are doing that job. Defence appears 23 times site-wide. Quality page lists DISP as (In progress).\n\nPRE-SEND CHECK, MANDATORY. Nobody is named anywhere on their site. Gary Busuttil came from the JOSCAR PDF's author metadata, which is the certificate ISSUER's file property, not anything B.B. Engineering published. Confirm on LinkedIn or open with the fallback greeting.",
  },
  {
    rank: 3,
    tier: 1,
    company: "Tynbell Sheetmetal Pty Ltd",
    channel: "DIDG",
    stage: "blocked",
    state: "NSW",
    domain: "NO WEBSITE",
    email: "sales@tynbell.com.au",
    emailSourceNote: "site no longer exists",
    contactName: "Raymond Fenech",
    nameVerified: "unverified",
    hook: "tynbell.com.au has no website at all: nameservers and MX exist, no A record.",
    hookVerified: "2026-08-07",
    hardWarning:
      "BLOCKED on the Spam Act consent basis. The address was collected while their site was up; the site is gone, so the publication that created inferred consent no longer exists. Sending on a lapsed basis is the only compliance exposure in this pipeline. Clear it by finding the address published live somewhere public today (ICN Gateway, Google Business Profile, a current AIC plan or directory), screenshotting it onto this record, then moving to queued. Otherwise make it LinkedIn only.",
    notes:
      "Confirmed by DNS. Nameservers exist (ns1 to ns4.melbourneit.net). An MX record points to tynbell-com-au.mail.protection.outlook.com, so their mail works and an email would deliver. There is no A record, so anyone typing the domain gets a browser error.\n\nA defence grant recipient with no website is the single largest unmet need in this pipeline, which is why it is worth the effort to clear the blocker. It is the best website prospect on the list.",
  },
  {
    rank: 4,
    tier: 1,
    company: "Rosebank Engineering Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Vic",
    domain: "rosebankeng.com.au",
    email: "info@rosebankeng.com.au",
    emailSourceNote: "contact page",
    contactName: "Aidan Butler-Bonnice",
    nameVerified: "directory",
    sentDate: "2026-08-06",
    followupDue: "2026-08-14",
    hook: "Their Surface Treatment page tells buyers to refer to the Capability Booklet, and no such document exists anywhere on their site.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "The sentence is plain text, not a link. There are ZERO PDFs across all 12 pages and the WordPress media library returns no documents at all. Every prospect who follows that instruction hits a dead end.\n\nThree pages linked in their own navigation are empty shells returning 200: /services/ (603 visible chars), /category/media-releases/ (600), /locations/ (608). The contact page address field contains only the company name, no street address. Footer reads 2022. The REST API returns zero posts; the newest date in prose is issued March 2015.\n\nSharpest detail: their Aerostructures page names their F-35 customer as UTC Aerospace Systems, a brand retired in November 2018, while their Fire Protection page uses the current name Collins Aerospace. Internally inconsistent on their flagship program.\n\nTempering: ASDAM-owned, so there may be a parent marketing function. Careers page points at hr-support@asdam.com.\n\nCorrection on file: an agent reported a user-agent decoy on this site. It did not reproduce on four different agents on 7 August. The note was stale.",
  },
  {
    rank: 5,
    tier: 1,
    company: "Universal Motion Simulation Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "Vic",
    domain: "unimotionsim.com",
    email: "info@unimotionsim.com",
    emailSourceNote: "footer, contact and about pages",
    contactName: "Dr Peter J Meikle",
    contactTitle: "Chief Executive Officer",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-14T08:39:00+10:00",
    hook: "A page called Test Post containing Lorem ipsum is live, publicly reachable and listed in their sitemap.",
    hookVerified: "2026-08-07",
    notes:
      "https://unimotionsim.com/test-post/ returns 200 and contains both Add Your Heading Text Here and Lorem ipsum dolor sit amet, consectetur adipiscing elit. It is listed in post-sitemap.xml, so search engines are being invited to index it, and it is reachable from their Essington Lewis award post via the previous link.\n\nThe more valuable finding: their homepage says PREFERRED supplier of driver simulators to the Australian Army; their about page says RECOMMENDED supplier. Two different claims about an Army relationship, in two places on the same site. For a defence supplier that is a claim-accuracy exposure, not a cosmetic one, and raising it shows the site was actually read.\n\nFooter copyright year is generated by JavaScript from the system clock, so it reads as current forever regardless of whether anyone maintains the site. WordPress 7.0.2, Elementor, built by Brown Ink. Deakin spinout. One PDF, a product spec sheet, no capability statement.",
  },
  {
    rank: 6,
    tier: 1,
    company: "One Ocean Group Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "WA",
    domain: "oneoceangroup.com.au",
    email: "info@oneoceangroup.com.au",
    emailSourceNote: "contact block and two mailto links",
    contactName: "Darren Kolln",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-13T11:47:00+10:00",
    hook: "Their site offers 10 percent off a first purchase for newsletter signup, on a vessel chartering business.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "Lands 9:47am Perth.\n\nVerbatim in the visible homepage text, directly above Copyright 2026 One Ocean Group. Leftover retail-template copy on a GoDaddy Website Builder site.\n\nSecond fault: every page load silently fetches their 4.8 MB vessel spec PDF by XMLHttpRequest before anyone clicks anything, reproduced twice. First visit weighs 5.8 MB across 83 requests. Slow on a phone, worse on a boat.\n\nZero defence mentions anywhere, despite offering guard vessel duties and safety standby operations. No dated content of any kind. Nobody named. Contact address is a PO Box only. Largest subcontract in its AIC plan.\n\nWhy rank 6: GoDaddy builder means no agency to displace, the fault is absurd and understood instantly by anyone, and the business is clearly bigger than its website.",
  },
  {
    rank: 7,
    tier: 1,
    company: "Owen International Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "NSW",
    domain: "owenint.com.au",
    email: "info@owenint.com.au",
    emailSourceNote: "header on every page",
    contactName: "Les Goodridge",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-12T08:52:00+10:00",
    hook: "Five accreditation badges each captioned New item, on every page.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "New item appears exactly 5 times in the homepage's visible text. The badges are ADIN, T-certified, ISO 9001, DISP and JOSCAR-AU: the strongest trust signals they have, each captioned with the unedited Gantry CMS placeholder, sitewide. All five also carry empty alt text, so screen readers and search engines find nothing there.\n\nFooter: 2018 to 2026 Owen International Website by Tube Media. Joomla 4/5 with Gantry 5. Veteran-owned since 1982, roughly 10 staff. Defence appears once on the homepage. No PDFs, no capability statement. Nobody named on the site. Most recent dated content 22 April 2025. No sitemap.xml.",
  },
  {
    rank: 8,
    tier: 2,
    company: "Kennewell Pty Ltd",
    channel: "DIDG",
    stage: "queued",
    state: "SA",
    domain: "kennewell.com",
    email: "emilien@kennewell.com",
    emailSourceNote: "footer",
    contactName: "Emilien",
    contactTitle: "Operations Manager",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-11T09:13:00+10:00",
    hook: "The Our Work item in their main navigation opens a case studies page with no case studies on it.",
    hookVerified: "2026-08-07",
    notes:
      "Note the domain is kennewell.com, not .com.au.\n\nThe nav label points to /case-studies/, which returns 611 visible characters against 3,211 for /services/. It contains the headings Stages, Design, Manufacturing and Finishing, and nothing beneath any of them. For a CNC machining business that is the page a buyer most wants and the only page showing them nothing.\n\nNo copyright year anywhere on the site. Elementor 4.2.2. Defence appears zero times.\n\nCorrection on file: an agent reported this page as a 404. It is not. All ten internal pages return 200. It renders empty, which is a worse fault and a more accurate claim.\n\nAddressee change from the old pipeline, which had Brett Kennewell at quotes@kennewell.com. Emilien is better: named on their own site, has a title, publishes a direct address. One contact per company, so Emilien is the record and Brett is not contacted.",
  },
  {
    rank: 9,
    tier: 2,
    company: "A.C.M. Laboratory Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "Vic",
    domain: "acmlab.com.au",
    email: "enquiries@acmlab.com.au",
    emailSourceNote: "contact page header",
    contactName: "Don Zhao",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-13T15:22:00+10:00",
    hook: "Running WordPress 4.9.1 from November 2017; footer still reads Copyright 2015.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "meta generator WordPress 4.9.1 is on the live homepage, and /readme.html is publicly readable so anyone confirms it in seconds. Roughly eight and a half years of security patches behind. Footer reads Copyright 2015 A.C.M Laboratory | All Rights Reserved | Powered by Dubbo Web Studio.\n\nAlso confirmed: both http://acmlab.com.au/ and http://www.acmlab.com.au/ return 200 with no redirect to HTTPS. Canonical and og:url both declare http. Their NATA accreditation mark and logo load over plain HTTP. The enquiry form on the HTTP version posts over plaintext.\n\nHANDLE THE HTTPS POINT CAREFULLY. Modern Chrome usually auto-upgrades these navigations, so the prospect may never see a Not secure warning and may push back. Defensible claims: no HTTPS redirect is configured, the canonical declares http, the NATA mark loads over plain HTTP. LEAD ON WordPress 4.9.1 AND Copyright 2015, which need no qualification.\n\nNATA accredited since 1968. Heaviest site checked, 3.3 MB across 32 assets. Nobody named. No PDFs at all, not even a scope-of-accreditation document.\n\nThis is the Coastal Aviation risk profile, one version further along. Worth saying so.",
  },
  {
    rank: 10,
    tier: 2,
    company: "Micron Manufacturing Pty Ltd",
    channel: "DIDG",
    stage: "queued",
    state: "NSW",
    domain: "micronmanufacturing.com.au",
    email: "info@micron.com.au",
    emailSourceNote: "homepage, contact and team pages",
    contactName: "Edward McMillan",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-10T14:19:00+10:00",
    hook: "Two items in their main menu, Results and Our Team, open empty pages.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "/results/ returns 638 visible characters, the navigation and footer only. /our-team/ returns 832 and names nobody. Compare the homepage at 7,994. Both sit in the navigation on every page.\n\nFooter reads Copyright Micron Manufacturing PTY LTD with NO year. WordPress 7.0.3, current. Defence appears zero times. Newest content 4 July 2016.\n\nADDRESS NOTE, easy to get backwards: the site is micronmanufacturing.com.au and micron.com.au redirects to it, but the address published on the site is info@micron.com.au. Use that one.",
  },
  {
    rank: 11,
    tier: 2,
    company: "Able Industries Engineering Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Vic",
    domain: "ableind.com.au",
    email: "enquiries@ableind.com.au",
    emailSourceNote: "published on their site",
    contactName: "Stephen Martyn",
    nameVerified: "directory",
    sentDate: "2026-08-04",
    followupDue: "2026-08-12",
    hook: "Their defence page carries 28 images and zero words, and the site mislabels DISP as DISP accredited.",
    hookVerified: "2026-07-31",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "RE-VERIFY BOTH BEFORE QUOTING. This is late-July research that has not been re-checked.\n\nThe DISP wording matters: DISP is membership at a level, never accreditation or certification. If it is still on their site it is a genuinely useful and slightly delicate thing to raise, and it is exactly the kind of error that makes the case for someone reviewing their public claims.",
  },
  {
    rank: 12,
    tier: 2,
    company: "Wessand Pty Ltd",
    tradingName: "Apparel Industries",
    channel: "DIDG",
    stage: "contacted",
    state: "NSW",
    domain: "apparelindustries.com.au",
    email: "info@apparelindustries.com.au",
    emailSourceNote: "published on their site",
    contactName: "Christopher Nguyen",
    nameVerified: "own-site",
    sentDate: "2026-08-04",
    followupDue: "2026-08-12",
    hook: "They manufacture ADF uniforms and the word defence does not appear on their website.",
    hookVerified: "2026-07-31",
    staleHook: true,
    notes:
      "RE-VERIFY THE ZERO-DEFENCE CLAIM BEFORE QUOTING IT.\n\nA GrantConnect-verified defence grant recipient whose site gives no indication they work in defence at all. Trading-name mismatch caught during ABN Lookup: the grant is under Wessand Pty Ltd, the business trades as Apparel Industries. Address the trading name.",
  },
  {
    rank: 13,
    tier: 2,
    company: "Lintek Pty Limited",
    channel: "DIDG",
    stage: "queued",
    state: "ACT",
    domain: "lintek.com.au",
    email: "sales@lintek.com.au",
    emailSourceNote: "contact page",
    contactName: "Renato Morosin",
    contactTitle: "Technical Sales",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-10T10:22:00+10:00",
    hook: "The capabilities PDF in their sitewide footer is the April 2020 version, while the current October 2024 version sits on the same server.",
    hookVerified: "2026-08-07",
    notes:
      "Footer Download Process Capabilities & DFM resolves to Design-Capabilities-v2.7.pdf, Last-Modified Tue 07 Apr 2020. The current Design-Capabilities-Version-3.7.5.pdf, Last-Modified Wed 09 Oct 2024, is linked ONLY from /products-and-capabilities/. The footer is on every page, so the default path hands buyers the four-year-old document.\n\nSecond fault: their careers page says more than 75% of product goes to defence, and defence appears zero times on the homepage.\n\nHeld back for a later touch: a homepage slider links to pathways.soldieron.org.au, a subdomain that no longer resolves; three job ads presented as current are dated October 2022; the contact mailto has a stray space after the colon; homepage weighs 3.8 MB.\n\nTempering: headcount around 50, at the top of the size filter. May have marketing capacity.",
  },
  {
    rank: 14,
    tier: 2,
    company: "Process Rubber and Plastics",
    tradingName: "PRP Manufacturing",
    channel: "DIDG",
    stage: "queued",
    state: "SA",
    domain: "prp.company",
    email: "info@prp.company",
    emailSourceNote: "footer, contact page and blog",
    contactName: "Luke Sernecki",
    contactTitle: "Chief Executive Officer",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-11T15:07:00+10:00",
    hardWarning:
      "NEVER reference the founder or company history in any communication with this company, ever. Their founder died in November 2021.",
    hook: "Their newest blog post opens 2025 is almost upon us, on a page whose footer reads 2026.",
    hookVerified: "2026-08-07",
    notes:
      "Verbatim on /blog-2024-year-in-review/. The annual series ran 2022, 2023, 2024 and stopped; no 2025 review exists. Their downloadable quad chart is still the April 2022 file: filename, PDF CreationDate 11 April 2022 and HTTP Last-Modified 24 October 2023 all agree. Capability brochure dates to 13 July 2021. Contact page lists Kent Town SA 5008; Kent Town is 5067.\n\nADDRESS CORRECTION. The old pipeline had luke@prp.company. That address is not published anywhere on their site. Only info@prp.company is. This was a known agent error, previously caught, and it must not be reintroduced.",
  },
  {
    rank: 15,
    tier: 2,
    company: "Cop-A-Mate Products Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Qld",
    domain: "copamate.com",
    email: "sales@copamate.com",
    emailSourceNote: "published on their site",
    contactName: "Jo",
    contactTitle: "role unconfirmed",
    nameVerified: "directory",
    sentDate: "2026-07-30",
    followupDue: "2026-08-07",
    hook: "Blank About page.",
    hookVerified: "2026-07-30",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "FOLLOW-UP OVERDUE. Due 7 to 9 August.\n\nFirst company contacted in the campaign. LinkedIn connect completed same day. The original email was fault-leading, which was the right instinct and was then abandoned for eight days.\n\nRE-VERIFY THE ABOUT PAGE BEFORE FOLLOWING UP. Nine days have passed.",
  },
  {
    rank: 16,
    tier: 2,
    company: "NH Micro Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "NSW",
    domain: "nhmicro.com",
    email: "mail@nhmicro.com",
    emailSourceNote: "published on their site",
    contactName: "Josh Hacko",
    contactTitle: "Technical Director",
    nameVerified: "own-site",
    sentDate: "2026-07-30",
    followupDue: "2026-08-07",
    hook: "Out-of-date website. TOO VAGUE TO SEND: re-verify a specific fault first.",
    hookVerified: "2026-07-30",
    staleHook: true,
    notes:
      "FOLLOW-UP OVERDUE. Due 7 to 9 August.\n\nLinkedIn connect completed same day. Josh Hacko confirmed still at NH Micro. The original email used the no-criticism shape at Kyle's explicit request.\n\nThe follow-up should now lead with the website, in line with the repositioning, but the specific fault needs re-verifying first. Out of date is too vague to send and is precisely the kind of line the repositioning was meant to replace.",
  },
  {
    rank: 17,
    tier: 2,
    company: "Decem Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "WA",
    domain: "decem.com.au",
    email: "admin@decem.com.au",
    emailSourceNote: "header, footer, about and contact pages",
    contactName: "Chris Clarke",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-12T11:24:00+10:00",
    hook: "Typing decem.com.au without https serves the entire site over an unencrypted connection with no redirect.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "Lands 9:24am Perth. Name is ICN Gateway sourced, so verify.\n\nhttp://decem.com.au/ returns 200 with a full 31,401-byte HTML page and NO Location header. HTTPS exists and its certificate is valid. The redirect is simply not configured. An HSTS header exists on HTTPS responses but cannot protect a first-time visitor arriving over HTTP.\n\nHand-built static site on nginx, no CMS. Copyright 2026 current. Defence appears 8 times. No dated content anywhere. No PDFs, no capability statement. Nobody named. Homepage 3.5 MB, mostly four large photographs. Veteran-owned, 18 staff, founded 2019.\n\nDO NOT RAISE the certificate common name (stage.decem.com.au). The SAN covers the domain correctly and browsers show no warning. Not a fault.\n\nWORDING CAUTION: the email says a business working on defence projects, not a DISP member. Their DISP level came from a third party and is not verified.",
  },
  {
    rank: 18,
    tier: 3,
    company: "Windows West Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "WA",
    domain: "windowswest.com.au",
    email: "sales@windowswest.com.au",
    emailSourceNote: "contact page and sitewide",
    contactName: "May Keven",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-11T11:38:00+10:00",
    hook: "The only document they offer for download is a quad chart, and the word defence appears nowhere on the site.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "Lands 9:38am Perth.\n\nA quad chart exists for exactly one audience. Homepage carries roughly 1,594 characters, the thinnest checked. Family-owned since 1994. Copyright 2026 current. Nobody named (approximately 15 to 20 local people). WordPress 7.0.3 with Elementor behind Cloudflare, built by Site Manage. Quad Chart PDF Last-Modified 1 December 2024.\n\nNo claim is made about the quad chart's contents: its text could not be reliably extracted.",
  },
  {
    rank: 19,
    tier: 3,
    company: "BVE Pty Ltd",
    tradingName: "Balvibe",
    channel: "AIC",
    stage: "queued",
    state: "NSW",
    domain: "balvibe.com.au",
    email: "orders@balvibe.com.au",
    emailSourceNote: "homepage and contact page",
    contactName: "Don Bailey",
    contactTitle: "Sales and Service",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-12T14:41:00+10:00",
    hook: "Homepage heading reads What's new and nothing on the site carries a date.",
    hookVerified: "2026-08-07",
    notes:
      "No copyright symbol, entity or the word copyright anywhere across homepage, company and contact pages. Newest product reference is 2023; newest image path /uploads/2023/08/. WordPress 7.0.2 with LiteSpeed, actively cached, so the site IS maintained, it is simply never dated. Defence appears zero times across five pages. Family-run, exports to NZ and PNG. Peter Bailey (Technical Support) also named. Only PDF is a Terms of Trade document.\n\nSoft fault, hence tier 3. The What's new contrast is what makes it land at all.",
  },
  {
    rank: 20,
    tier: 3,
    company: "Puzzle Precision Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "NSW",
    domain: "puzzleprecision.com.au",
    email: "puzzle@puzzleprecision.com.au",
    emailSourceNote: "contact page and footer",
    contactName: "Craig Coburn",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-13T09:18:00+10:00",
    hook: "Nothing on the site can be downloaded: no capability statement, no datasheet.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "Zero PDFs across all four pages. The only file offered is a set of GPG public keys. Footer reads a copyright symbol, Puzzle Precision Pty Ltd, ABN 84 166 982 912: symbol present, NO year. No dated content anywhere.\n\nTheir own copy: Puzzle Precision is at the forefront of electronic assembly with a strong focus on the critical reliability and defence markets. Ten staff, Cardiff NSW.\n\nTempering: Next.js on nginx, the most modern stack in the pipeline. Someone competent built this recently, which lowers the odds they are shopping. Three pages exist in the sitemap but not in the navigation.",
  },
  {
    rank: 21,
    tier: 3,
    company: "Currawong Engineering Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Tas",
    domain: "currawong.aero",
    email: "admin@currawong.aero",
    emailSourceNote: "published on their site",
    contactName: "Gavin Brett",
    nameVerified: "directory",
    sentDate: "2026-08-03",
    followupDue: "2026-08-11",
    hook: "Land Forces exhibitor, timing-led.",
    hookVerified: "2026-07-31",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.",
  },
  {
    rank: 22,
    tier: 3,
    company: "Ron Allum Deepsea Services Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "NSW",
    domain: "ronallum.com",
    email: "enquiries@ronallum.com",
    emailSourceNote: "published on their site",
    contactName: "Ron Allum",
    nameVerified: "own-site",
    sentDate: "2026-08-03",
    followupDue: "2026-08-11",
    hook: "Ghost Shark partner with an old site.",
    hookVerified: "2026-07-31",
    staleHook: true,
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.\n\nAddressee switched to Ron after Damian Mackey proved unfindable.",
  },
  {
    rank: 23,
    tier: 3,
    company: "KBE Pty Ltd",
    tradingName: "Summers Engineering",
    channel: "DIDG",
    stage: "contacted",
    state: "SA",
    domain: "summersengineering.com.au",
    email: "sales@summersengineering.com.au",
    emailSourceNote: "published on their site",
    contactName: "James Tononcelli",
    nameVerified: "directory",
    sentDate: "2026-08-03",
    followupDue: "2026-08-11",
    hook: "Trading-name mismatch found via ABN Lookup.",
    hookVerified: "2026-07-31",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.",
  },
  {
    rank: 24,
    tier: 3,
    company: "Rivierra Pty Ltd",
    tradingName: "Australian General Engineering",
    channel: "DIDG",
    stage: "contacted",
    state: "Vic",
    domain: "austgen.com.au",
    email: "sales@austgen.com.au",
    emailSourceNote: "published on their site",
    contactName: "Con Litsios",
    nameVerified: "directory",
    sentDate: "2026-08-04",
    followupDue: "2026-08-12",
    hook: "Trading-name mismatch; headcount flag, verify under 50.",
    hookVerified: "2026-07-31",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.",
  },
  {
    rank: 25,
    tier: 3,
    company: "Value Heat Treatment Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "Vic",
    domain: "valueheattreatment.com.au",
    email: "info@valueheattreatment.com.au",
    emailSourceNote: "published on their site",
    contactName: "Raj Kumar",
    nameVerified: "directory",
    sentDate: "2026-08-07",
    followupDue: "2026-08-15",
    hook: "Most recent send. The last of the capability-statement emails.",
    hookVerified: "2026-07-31",
    staleHook: true,
    fallbackGreeting: "Good morning,",
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.\n\nThe last email sent under the old capability-statement positioning.",
  },
  {
    rank: 26,
    tier: 3,
    company: "Micca Holdings Pty Ltd",
    tradingName: "Micks Ally Fab",
    channel: "DIDG",
    stage: "contacted",
    state: "NT",
    domain: "mafnt.com.au",
    email: "admin@mafnt.com.au",
    emailSourceNote: "published on their site",
    contactName: "Mick Carey",
    contactTitle: "Managing Director",
    nameVerified: "directory",
    sentDate: "2026-07-31",
    followupDue: "2026-08-08",
    hook: "Trading-name mismatch.",
    hookVerified: "2026-07-31",
    staleHook: true,
    hardWarning:
      "NO LinkedIn presence. Email only. Do not attempt a connect request.",
    notes:
      "Late-July research, NOT re-verified. Re-check the fault before quoting it.\n\nFollow-up due 8 to 10 August.",
  },
  {
    rank: 27,
    tier: 3,
    company: "Protonautics Pty Ltd",
    channel: "DIDG",
    stage: "contacted",
    state: "NSW",
    domain: "protonautics.com",
    email: "info@protonautics.com",
    emailSourceNote: "published on their site",
    contactName: "Ed Bub",
    nameVerified: "directory",
    sentDate: "2026-08-05",
    followupDue: "2026-08-13",
    hook: "Copyright 2026 is current but there is no dated content anywhere, no capability statement and nobody named.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes: "Fault re-verified 7 August.",
  },
  {
    rank: 28,
    tier: 3,
    company: "Teklada Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "Vic",
    domain: "teklada.com",
    email: "support@teklada.com",
    emailSourceNote: "homepage and contact page",
    contactName: "Parth Paradkar",
    contactTitle: "Co-founder",
    nameVerified: "own-site",
    scheduledSendAt: "2026-08-14T13:16:00+10:00",
    hook: "Newest blog post dated 25 November 2024, while case studies show January 2026.",
    hookVerified: "2026-08-07",
    notes:
      "Confirmed on /blog/; every other post there falls between September and November 2024. Their case studies page carries a 27 January 2026 item, so the site is maintained and the blog specifically is not: twenty months silent. Copyright 2026 current. Zero defence mentions. No PDFs anywhere. Juan du Toit is the other co-founder.\n\nWhy tier 3 despite a clean fault: WordPress with Elementor built by Geolix, plus HubSpot tracking and Yoast. They have an agency and a marketing stack. They know the blog is stale and have chosen other priorities. Low odds a cold email changes that.\n\nUnverifiable: one of eleven LinkedIn profile links appeared dead, but LinkedIn blocks automated checks. Do not raise it.",
  },
  {
    rank: 29,
    tier: 3,
    company: "SecureWare Pty Ltd",
    channel: "AIC",
    stage: "queued",
    state: "SA",
    domain: "secureware.com.au",
    email: "info@secureware.com.au",
    emailSourceNote: "contact page and footer",
    contactName: "Adam Barker",
    nameVerified: "directory",
    scheduledSendAt: "2026-08-17T09:41:00+10:00",
    hook: "The Latest News Updates block on their homepage has a newest item from 13 July 2023.",
    hookVerified: "2026-08-07",
    fallbackGreeting: "Good morning,",
    notes:
      "Verified in a real browser: this site sits behind an Imperva WAF that blocks scripted access. /news/ shows ANNOUNCEMENT | JUL 13, 2023, Secureware's 4th appearance in the CRN Fast50, as newest; the two behind it are from 2019. /contact/ publishes info@secureware.com.au with 311 Portrush Road, Norwood SA 5067. Copyright 2026 current.\n\nZero defence-sector mentions; the single defence string is defences in the cyber sense. Only one PDF sitewide, a terms document. A /capabilities/ page exists offering no downloadable capability statement.\n\nSecond angle: nobody from Secureware is named on the site, while FIVE clients have put their names to testimonials: SA Power Networks, McMahon Services, Bedford Group, St Peter's Girls' School, Seymour College, REDARC. That asymmetry is the sharper observation.\n\nOn the name: two testimonials refer to Adam and his team and dealing with Adam over the last 15 or so years, corroborating an Adam in a senior client-facing role. Reasonably safe, still worth ten seconds on LinkedIn.\n\nWhy tier 3: Imperva WAF, an agency (Argon), and a client list of that quality mean budget and an incumbent provider.",
  },
  {
    rank: 30,
    tier: 3,
    company: "Luminact Pty Ltd",
    channel: "DIDG",
    stage: "linkedin_only",
    state: "Vic",
    domain: "luminact.com.au",
    email: "andrew.skinner@luminact.com.au",
    emailSourceNote: "contact page",
    contactName: "Andrew Skinner",
    contactTitle: "Director",
    nameVerified: "own-site",
    sentDate: "2026-08-05",
    hardWarning:
      "LinkedIn only, by Kyle's instruction. No further email to this company.",
    hook: "Their homepage White papers link returns a 404 while the real white papers are live elsewhere on the same site.",
    hookVerified: "2026-08-07",
    notes:
      "Hook is for the LinkedIn note only.\n\nAlso verified: /contact-us/ returns 404 and is orphaned, not linked from anywhere on their own site, so it only harms people arriving from old links or search results. A navigation item labelled Land Forces 2024 appears on every page and opens a page still reading Land Forces 24 is shaping up to be even better! in future tense, roughly 23 months after the event.\n\nPREMISE CORRECTION ON FILE: an earlier note claimed Luminact publishes no email address. That was wrong. They publish four, including three named directors. Do not use you have no email on your site with this company.\n\nFreshest site in the pipeline (newest content 17 December 2025, an NZ MoD appointment), most substantive copy, three directors named, two offices. The most sophisticated company on the list, which is why email is closed and LinkedIn stays open.",
  },
];

/**
 * Companies with no usable email, kept so they are not re-derived or lost.
 * Under the old capability-statement offer they were correctly parked; under a
 * website-led offer they are the highest-need prospects available. None can
 * enter the pipeline until an address is published somewhere public.
 */
export const PARKED_NO_EMAIL = [
  {
    company: "Endurance Hydrographic",
    channel: "AIC",
    situation: "Domain parked, no site",
    routeIn:
      "LinkedIn only, Jacob Hamilton. The government PDF that published their address was withdrawn, so there is no email consent basis.",
  },
  {
    company: "Hydro Sight",
    channel: "AIC",
    situation: "Domain parked, no site",
    routeIn: "LinkedIn only, Lachlan Stone-Schack. Same withdrawn-PDF problem.",
  },
  {
    company: "Airspeed Pty Ltd",
    channel: "AIC",
    situation: "Site live, contact form only",
    routeIn:
      "Highest value of the three. Check the CASA registry for a published address. BAE Hunter Class and MQ-28 Ghost Bat radome work.",
  },
];
