/**
 * The Ironpeak pipeline as handed over on 7 August 2026, emails included.
 *
 * GENERATED from portal-handoff-pipeline.md by scripts/gen-pipeline.py. Do not
 * hand-edit: change the markdown and regenerate.
 *
 * Generated rather than transcribed on purpose. Nineteen email bodies retyped
 * by hand is nineteen chances to change a word Kyle chose, and the shape of
 * these emails is deliberate down to the phrasing he has explicitly rejected.
 * Parsing keeps them byte for byte.
 *
 * This REPLACES every earlier dataset. The previous files held 76 records of
 * which 51 were triaged out; those are gone deliberately.
 */

export type PipelineStage = "contacted" | "queued" | "blocked" | "linkedin_only";
export type EmailStatus = "ready" | "held" | "not-written";

export interface PipelineRecord {
  rank: number;
  tier: 1 | 2 | 3;
  company: string;
  channel: "DIDG" | "AIC";
  stage: PipelineStage;
  state: string;
  /** "NO WEBSITE" is a valid and important value. */
  domain: string;
  email: string;
  contactName: string;
  nameVerified: "own-site" | "directory" | "unverified";
  fallbackGreeting: string | null;
  sentDate: string | null;
  followupDue: string | null;
  scheduledSendAt: string | null;
  /** Coastal Aviation only: send on receipt, overriding the day 8 to 10 window. */
  sendImmediately: boolean;
  hook: string;
  hookVerified: string | null;
  emailStatus: EmailStatus;
  emailSubject: string | null;
  /** Verbatim. The signature and opt-out are appended at send, not stored. */
  emailBody: string | null;
  emailBlocker: string | null;
  emailSourceNote: string;
  /** Shown as a warning that cannot be dismissed. */
  hardWarning: string | null;
  notes: string;
}

export const PIPELINE_V2: PipelineRecord[] = [
  {
    "rank": 1,
    "tier": 1,
    "company": "Coastal Aviation Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Tas",
    "domain": "coastalaviation.com.au",
    "email": "info@coastalaviation.com.au",
    "contactName": "Robert Stowe",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-05",
    "followupDue": "2026-08-13",
    "scheduledSendAt": null,
    "sendImmediately": true,
    "hook": "their website is compromised and serving pharmacy spam.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your website is showing pharmacy spam to visitors",
    "emailBody": "Hi Robert,\n\nI wrote last week about capability material. Set that aside, because I found\nsomething more urgent.\n\nYour homepage is currently displaying pharmacy spam to visitors. It sits\ndirectly under the Part 145 paragraph, in the visible text: \"köpa viagra i\nsverige\", \"cialis online\", and links out to four sites. Anyone loading\ncoastalaviation.com.au right now sees it, and so does Google.\n\nThe likely cause is the WordPress version. You're on 4.8.25, which is around\nnine years old. Whoever maintains the site can confirm, but injected links\nthat are invisible in the admin and visible on the page are the standard\npattern for a compromised install.\n\nTwo things worth doing today: tell your host, and check Google Search Console\nfor a security notice.\n\nI'm not pitching you a clean-up. Any competent WordPress person can fix it.\nI'd rather you heard it from someone than found out when a customer mentioned\nit.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): their website is compromised and serving pharmacy spam. WordPress 4.8.25, released around 2017. In the visible text, directly beneath their Part 145 paragraph: viagra x3, cialis x3, phenq x1, farmacia x3, with seven live outbound links to euro2000.org, mifarmacia24.com, farmaciaespana247.com and sportzfuel.com. Verbatim: \"Our Part 145 approval covers component maintenance and overhaul, machining, sheet-metal and welding. köpa viagra i sverige, this site, cialis online, Euro2000 viagra...\" A broken shortcode [products columns=6 paginate=true limit=6] also prints raw on the page. Why rank 1. The only true painkiller in the pipeline. Actively damaging them now, verifiable by them in ten seconds, and telling them is a favour regardless of whether it produces work."
  },
  {
    "rank": 2,
    "tier": 1,
    "company": "B.B. Engineering Pty Ltd",
    "channel": "DIDG",
    "stage": "queued",
    "state": "Vic",
    "domain": "bbengineering.com.au",
    "email": "sales@bbengineering.com.au",
    "contactName": "Gary Busuttil",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-10T08:47:00+10:00",
    "sendImmediately": false,
    "hook": "their JOSCAR-AU certificate, displayed on their own homepage, shows Renewal Date: 11 August 2026.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your JOSCAR-AU certificate shows a renewal date of 11 August",
    "emailBody": "Hi Gary,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nThe JOSCAR-AU certificate displayed on your homepage carries a renewal date\nof 11 August 2026, which is Tuesday. If that is already in train, ignore me.\nIf it is not, it is worth knowing, because a prime checking your registration\nis looking at that page.\n\nSeparately, there is no capability statement on the site. The two certificates\nare doing that job instead, which works right up until someone wants a document\nthey can forward internally.\n\nWebsites and capability material are what I do. If either is on your list this\nyear I am glad to talk, and if not that is completely fine.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): their JOSCAR-AU certificate, displayed on their own homepage, shows Renewal Date: 11 August 2026. The certificate image JOSCAR-AU-Cert.jpg was downloaded from their homepage and read directly. It reads \"Renewal Date: 11 August 2026\" beneath Colin Maund, CEO, Hellios Information. That is the day after the scheduled send. Hand-built PHP, no CMS, so no incumbent agency. Copyright © 2026 current. Only two PDFs, both certificates, no capability statement. Defence x23 site-wide. Quality page lists DISP as \"(In progress)\"."
  },
  {
    "rank": 3,
    "tier": 1,
    "company": "Tynbell Sheetmetal Pty Ltd",
    "channel": "DIDG",
    "stage": "blocked",
    "state": "NSW",
    "domain": "NO WEBSITE",
    "email": "sales@tynbell.com.au",
    "contactName": "Raymond Fenech",
    "nameVerified": "unverified",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "tynbell.com.au has no website at all.",
    "hookVerified": "2026-08-07",
    "emailStatus": "held",
    "emailSubject": "tynbell.com.au is not loading",
    "emailBody": "Hi Raymond,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence and manufacturing suppliers.\n\nYour domain tynbell.com.au currently has no website attached to it. The domain\nis still yours and your mail is working, which is how this is reaching you, but\nthere is no address record pointing anywhere, so anyone typing it into a browser\ngets an error rather than a page.\n\nI do not know whether that is deliberate, a lapsed hosting account, or a DNS\nchange that did not finish. Whoever manages the domain for you can tell you in\nabout a minute.\n\nWebsites are what I do, if it turns out you need one. If not, at least you know.",
    "emailBlocker": "Email written but HELD. It may not be sent until its blocker clears.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": "BLOCKED on the Spam Act consent basis. The address was collected while their site was up; the site is gone, so the publication that created inferred consent no longer exists. Clear it by finding the address published live somewhere public today, screenshotting it onto this record, then moving to queued.",
    "notes": "Email written but HELD. It may not be sent until its blocker clears.\n\nemail_status: held Hook (verified 2026-08-07): tynbell.com.au has no website at all. Confirmed by DNS. Nameservers exist (ns1 to ns4.melbourneit.net). An MX record exists pointing to tynbell-com-au.mail.protection.outlook.com, so their mail works and an email would deliver. But there is no A record, so anyone typing the domain gets a browser error. A defence grant recipient with no website is the largest unmet need in this pipeline."
  },
  {
    "rank": 4,
    "tier": 1,
    "company": "Rosebank Engineering Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Vic",
    "domain": "rosebankeng.com.au",
    "email": "info@rosebankeng.com.au",
    "contactName": "Aidan Butler-Bonnice",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-06",
    "followupDue": "2026-08-14",
    "scheduledSendAt": "2026-08-14T09:26:00+10:00",
    "sendImmediately": false,
    "hook": "their Surface Treatment page tells buyers to \"refer to the Capability Booklet\", and no such document exists anywhere on their site.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "The Capability Booklet your site refers to does not exist",
    "emailBody": "Hi Aidan,\n\nKyle Hartwell here. I wrote last week about capability material. One specific\nthing since then.\n\nYour Surface Treatment page tells readers that for full details of capabilities\nand accreditations at each of your finishing sites, they should refer to the\nCapability Booklet. There is no such document anywhere on the site. The line is\nplain text rather than a link, and there are no PDFs at all across any of your\ntwelve pages, so anyone who follows that instruction reaches a dead end.\n\nThree pages in your own navigation are also empty. Services, Media Releases and\nLocations each load and show nothing.\n\nWebsites and capability material are what I do. Happy to talk if useful, and no\ntrouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): their Surface Treatment page tells buyers to \"refer to the Capability Booklet\", and no such document exists anywhere on their site. The sentence is plain text, not a link. Zero PDFs across all 12 pages, and the WordPress media library returns no documents at all. Three pages linked in their own navigation are empty shells returning 200: /services/ (603 visible chars), /category/media-releases/ (600), /locations/ (608). The contact page's address field contains only the company name. Footer reads 2022. REST API returns zero posts. Sharpest detail: their Aerostructures page names their F-35 customer as \"UTC Aerospace Systems\", a brand retired in November 2018, while their Fire Protection page uses the current name Collins Aerospace. Tempering: ASDAM-owned, so a parent marketing function may exist. Careers points at hr-support@asdam.com."
  },
  {
    "rank": 5,
    "tier": 1,
    "company": "Universal Motion Simulation Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "Vic",
    "domain": "unimotionsim.com",
    "email": "info@unimotionsim.com",
    "contactName": "Dr Peter J Meikle",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-14T08:39:00+10:00",
    "sendImmediately": false,
    "hook": "a page called Test Post containing Lorem ipsum is live, publicly reachable and listed in their sitemap.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "A page called Test Post is live on your site",
    "emailBody": "Good morning Dr Meikle,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nThere is a page on your site at /test-post/ containing the words \"Add Your\nHeading Text Here\" and a paragraph of Lorem ipsum. It returns a normal page\nrather than a not found, it is listed in your sitemap so search engines are\nbeing invited to index it, and it is reachable from the Essington Lewis award\npost through the previous link.\n\nOne other thing worth knowing. Your homepage says preferred supplier of driver\nsimulators to the Australian Army. Your about page says recommended supplier.\nThose are different claims to be making in two places.\n\nWebsites are what I do. Happy to talk if useful.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): a page called Test Post containing Lorem ipsum is live, publicly reachable and listed in their sitemap. https://unimotionsim.com/test-post/ returns 200 and contains both \"Add Your Heading Text Here\" and \"Lorem ipsum dolor sit amet, consectetur adipiscing elit.\" Listed in post-sitemap.xml, so search engines are invited to index it, and reachable from their Essington Lewis award post via the previous link. The more valuable finding: their homepage says preferred supplier of driver simulators to the Australian Army; their about page says recommended supplier. Two different claims about an Army relationship on the same site. For a defence supplier that is a claim-accuracy exposure, not a cosmetic one. Footer copyright year is JavaScript-generated from the system clock, so it reads as current forever regardless of maintenance. WordPress 7.0.2, Elementor, built by Brown Ink. Deakin spinout. One PDF, a product spec sheet, no capability statement."
  },
  {
    "rank": 6,
    "tier": 1,
    "company": "One Ocean Group Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "WA",
    "domain": "oneoceangroup.com.au",
    "email": "info@oneoceangroup.com.au",
    "contactName": "Darren Kolln",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-13T11:47:00+10:00",
    "sendImmediately": false,
    "hook": "their site offers \"Get 10% off your first purchase when you sign up for our newsletter!\" — on a vessel chartering business.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your site offers 10% off a first purchase",
    "emailBody": "Hi Darren,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian marine\nand defence suppliers.\n\nNear the bottom of your homepage the site says \"Get 10% off your first purchase\nwhen you sign up for our newsletter!\". That is leftover copy from the retail\ntemplate the site was built on, and it is live on a vessel chartering business.\n\nTwo others while I was there. Every visit quietly downloads your 4.8 megabyte\nvessel spec PDF before anyone has clicked anything, which is slow on a phone and\nslower on a boat. And the word defence appears nowhere on the site.\n\nWebsites are what I do. Happy to talk if that is useful, and no trouble at all\nif not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): their site offers \"Get 10% off your first purchase when you sign up for our newsletter!\" — on a vessel chartering business. Verbatim in the visible homepage text, directly above \"Copyright © 2026 One Ocean Group\". Leftover retail-template copy on a GoDaddy Website Builder site. Second fault: every page load silently fetches their 4.8 MB vessel spec PDF by XMLHttpRequest before anyone clicks anything, reproduced twice. First visit weighs 5.8 MB across 83 requests. Zero defence mentions despite offering guard vessel duties and safety standby operations. No dated content. Nobody named. PO Box only. Largest subcontract in its AIC plan. Why tier 1. GoDaddy builder means no agency to displace, the fault is absurd and understood instantly, and the business is clearly bigger than its website."
  },
  {
    "rank": 7,
    "tier": 1,
    "company": "Owen International Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "NSW",
    "domain": "owenint.com.au",
    "email": "info@owenint.com.au",
    "contactName": "Les Goodridge",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-12T08:52:00+10:00",
    "sendImmediately": false,
    "hook": "five accreditation badges captioned \"New item\" on every page.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Five accreditation badges on your site are captioned \"New item\"",
    "emailBody": "Hi Les,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nThe five accreditation badges in your site footer, ADIN, ISO 9001, DISP, JOSCAR\nand the T mark, are each captioned \"New item\". That is the placeholder your CMS\ninserts when a caption is left blank, and it appears under all five badges on\nevery page of the site. They are the strongest trust signals you have and they\ncurrently read as unfinished.\n\nThey also carry no alt text, so a screen reader and a search engine both find\nnothing there at all.\n\nWebsites are what I do. Happy to talk if that is worth fixing properly, and no\ntrouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): five accreditation badges captioned \"New item\" on every page. \"New item\" appears exactly 5 times in the homepage's visible text. The badges are ADIN, T-certified, ISO 9001, DISP and JOSCAR-AU — the strongest trust signals they have, each captioned with the unedited Gantry CMS placeholder, sitewide. All five also carry empty alt text. Footer: \"© 2018 - 2026 Owen International Website by Tube Media\". Joomla 4/5 with Gantry 5. Veteran-owned since 1982, roughly 10 staff. Defence x1 on the homepage. No PDFs, no capability statement. Nobody named. Newest dated content 22 April 2025. No sitemap.xml."
  },
  {
    "rank": 8,
    "tier": 2,
    "company": "Kennewell Pty Ltd",
    "channel": "DIDG",
    "stage": "queued",
    "state": "SA",
    "domain": "kennewell.com",
    "email": "emilien@kennewell.com",
    "contactName": "Emilien",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-11T09:13:00+10:00",
    "sendImmediately": false,
    "hook": "the \"Our Work\" item in their main navigation opens a page with no work on it.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your Our Work page has no work on it",
    "emailBody": "Hi Emilien,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\nmachining and manufacturing businesses.\n\n\"Our Work\" sits in your main navigation on every page. The page it opens has\nthe headings Stages, Design, Manufacturing and Finishing, and then nothing\nunderneath any of them. For a CNC shop that is the page a buyer most wants to\nsee, and at the moment it is the one page that shows them nothing at all.\n\nThe site also carries no copyright year anywhere, and the word defence does not\nappear on it.\n\nWebsites are what I do. If getting some actual work onto that page is on your\nlist, I am happy to talk. If not, no trouble.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): the \"Our Work\" item in their main navigation opens a page with no work on it. The nav label points to /case-studies/, which returns 611 visible characters against 3,211 for /services/. It contains the headings Stages, Design, Manufacturing and Finishing, and nothing beneath any of them. No copyright year anywhere. Elementor 4.2.2. Defence x0. Correction on file. An agent reported this page as a 404. It is not — all ten internal pages return 200. It renders empty, which is a worse fault and a more accurate claim. Addressee change from the old pipeline. It had Brett Kennewell at quotes@kennewell.com. Emilien is better: named on their own site, has a title, publishes a direct address. One contact per company, so Emilien is the record and Brett is never contacted."
  },
  {
    "rank": 9,
    "tier": 2,
    "company": "A.C.M. Laboratory Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "Vic",
    "domain": "acmlab.com.au",
    "email": "enquiries@acmlab.com.au",
    "contactName": "Don Zhao",
    "nameVerified": "directory",
    "fallbackGreeting": "Good afternoon,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-13T15:22:00+10:00",
    "sendImmediately": false,
    "hook": "running WordPress 4.9.1, released November 2017.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your site is running WordPress from 2017",
    "emailBody": "Hi Don,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian labs\nand manufacturers.\n\nYour website runs WordPress 4.9.1, released in November 2017. That is around\neight and a half years of security patches behind. Outdated WordPress is far\nand away the most common way a small business site gets quietly turned into\nsomething else. I came across an Australian aerospace maintenance business this\nweek whose homepage had been filled with pharmacy spam exactly that way, and\nthey had no idea.\n\nThe footer also still reads \"Copyright 2015\", and your server does not redirect\nvisitors to the secure version of the site, so your NATA mark loads over a plain\nconnection.\n\nWebsites are what I do. If this is worth sorting out, I am happy to talk.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): running WordPress 4.9.1, released November 2017. <meta name=\"generator\" content=\"WordPress 4.9.1\" /> confirmed on the live homepage, and /readme.html is publicly readable so anyone confirms it in seconds. Roughly eight and a half years of security patches behind. Footer still reads \"Copyright 2015 A.C.M Laboratory | All Rights Reserved | Powered by Dubbo Web Studio\". Also confirmed: both http://acmlab.com.au/ and http://www.acmlab.com.au/ return 200 with no redirect to HTTPS. Canonical and og:url both declare http://. Their NATA mark and logo load over plain HTTP. NATA accredited since 1968. Heaviest site checked, 3.3 MB across 32 assets. Nobody named. No PDFs at all, not even a scope-of-accreditation document."
  },
  {
    "rank": 10,
    "tier": 2,
    "company": "Micron Manufacturing Pty Ltd",
    "channel": "DIDG",
    "stage": "queued",
    "state": "NSW",
    "domain": "micronmanufacturing.com.au",
    "email": "info@micron.com.au",
    "contactName": "Edward McMillan",
    "nameVerified": "directory",
    "fallbackGreeting": "Good afternoon,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-10T14:19:00+10:00",
    "sendImmediately": false,
    "hook": "two items in their main menu open empty pages.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Two pages in your menu are empty",
    "emailBody": "Hi Edward,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\nmanufacturers selling into defence.\n\nTwo items in your main menu open pages with nothing on them. \"Results\" is a\nheading and then the footer. \"Our Team\" is a heading, then a list of links back\nto other pages, with nobody named on it. Both sit in the navigation on every\npage, so they are easy for a visitor to click and easy for you to never see.\n\nThe footer copyright also carries no year at all, which is small, but it is the\nfirst place people look to work out whether a site is still being kept up.\n\nWebsites are what I do. Happy to talk if that is useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): two items in their main menu open empty pages. /results/ returns 638 visible characters — navigation and footer only. /our-team/ returns 832 and names nobody. Compare the homepage at 7,994. Both sit in the navigation on every page. Footer reads \"Copyright © Micron Manufacturing PTY LTD\" with no year. WordPress 7.0.3, current. Defence x0. Newest content 4 July 2016. Address note, easy to get backwards: the site is micronmanufacturing.com.au and micron.com.au redirects to it, but the address published on the site is info@micron.com.au."
  },
  {
    "rank": 11,
    "tier": 2,
    "company": "Able Industries Engineering Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Vic",
    "domain": "ableind.com.au",
    "email": "enquiries@ableind.com.au",
    "contactName": "Stephen Martyn",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-04",
    "followupDue": "2026-08-12",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "defence page carries 28 images and zero words, and the site mislabels DISP as \"DISP accredited\".",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": "No email written: the fault is late-July research and may not be quoted without re-verification.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "No email written: the fault is late-July research and may not be quoted without re-verification.\n\nHook (research late July, NOT re-verified): defence page carries 28 images and zero words, and the site mislabels DISP as \"DISP accredited\"."
  },
  {
    "rank": 12,
    "tier": 2,
    "company": "Wessand Pty Ltd (t/a Apparel Industries)",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "NSW",
    "domain": "apparelindustries.com.au",
    "email": "info@apparelindustries.com.au",
    "contactName": "Christopher Nguyen",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": "2026-08-04",
    "followupDue": "2026-08-12",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "they manufacture ADF uniforms and the word defence does not appear on their website.",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": "No email written: the fault is late-July research and may not be quoted without re-verification.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "No email written: the fault is late-July research and may not be quoted without re-verification.\n\nHook (research late July, NOT re-verified): they manufacture ADF uniforms and the word defence does not appear on their website. A GrantConnect-verified defence grant recipient whose site gives no indication they work in defence. Trading-name mismatch caught via ABN Lookup: the grant is under Wessand Pty Ltd, the business trades as Apparel Industries. Address the trading name."
  },
  {
    "rank": 13,
    "tier": 2,
    "company": "Lintek Pty Limited",
    "channel": "DIDG",
    "stage": "queued",
    "state": "ACT",
    "domain": "lintek.com.au",
    "email": "sales@lintek.com.au",
    "contactName": "Renato Morosin",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-10T10:22:00+10:00",
    "sendImmediately": false,
    "hook": "the capabilities PDF in their sitewide footer is the April 2020 version, while the current October 2024 version sits on the same server.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "The capabilities PDF in your footer is the 2020 version",
    "emailBody": "Hi Renato,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nThe \"Download Process Capabilities & DFM\" link in your site footer serves\nDesign Capabilities v2.7, dated April 2020. Your current version 3.7.5 from\nOctober 2024 sits on the same server, but it is linked from the capabilities\npage only. Anyone who takes the footer link, which is on every page, gets the\nfour year old one.\n\nThe other thing I noticed is that your careers page says more than 75 per cent\nof your product goes to the defence industry, and the word does not appear on\nyour homepage at all.\n\nWebsites are what I do. Happy to talk if it is useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): the capabilities PDF in their sitewide footer is the April 2020 version, while the current October 2024 version sits on the same server. Footer \"Download Process Capabilities & DFM\" resolves to Design-Capabilities-v2.7.pdf, Last-Modified: Tue, 07 Apr 2020. The current Design-Capabilities-Version-3.7.5.pdf, Last-Modified: Wed, 09 Oct 2024, is linked only from /products-and-capabilities/. The footer is on every page, so the default path hands buyers the four-year-old document. Second fault: their careers page says more than 75% of product goes to defence, and defence appears zero times on the homepage. Held back for a later touch: a homepage slider links to pathways.soldieron.org.au, a subdomain that no longer resolves; three job ads presented as current are dated October 2022; the contact mailto has a stray space after the colon; homepage weighs 3.8 MB. Tempering: headcount around 50, top of the size filter. May have marketing capacity."
  },
  {
    "rank": 14,
    "tier": 2,
    "company": "Process Rubber and Plastics (PRP Manufacturing)",
    "channel": "DIDG",
    "stage": "queued",
    "state": "SA",
    "domain": "prp.company",
    "email": "info@prp.company",
    "contactName": "Luke Sernecki",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-11T15:07:00+10:00",
    "sendImmediately": false,
    "hook": "their newest blog post opens \"2025 is almost upon us\", on a page whose footer reads 2026.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your newest blog post opens with \"2025 is almost upon us\"",
    "emailBody": "Hi Luke,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nThe most recent article on your blog is the 2024 Year in Review, and its\nopening line is \"2025 is almost upon us\". The footer on that same page reads\n2026. Your quad chart is still the April 2022 file, and the capability brochure\ndates to July 2021.\n\nOne small thing while I was there. The contact page lists Kent Town SA 5008.\nKent Town is 5067.\n\nNone of it is urgent. But the quad chart is the document primes actually open,\nand yours is four years old.\n\nWebsites and capability material are what I do. Happy to talk if useful.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": "NEVER reference the founder or company history in any communication with this company, ever. Their founder died in November 2021.",
    "notes": "Hook (verified 2026-08-07): their newest blog post opens \"2025 is almost upon us\", on a page whose footer reads 2026. Verbatim on /blog-2024-year-in-review/. The annual series ran 2022 → 2023 → 2024 and stopped. Their downloadable quad chart is still the April 2022 file — filename, PDF CreationDate 11 April 2022 and HTTP Last-Modified 24 October 2023 all agree. Capability brochure dates to 13 July 2021. Contact page lists Kent Town SA 5008; Kent Town is 5067. ADDRESS CORRECTION — do not reintroduce. The old pipeline had luke@prp.company. That address is not published anywhere on their site. Only info@prp.company is. This was a known agent error, previously caught once already."
  },
  {
    "rank": 15,
    "tier": 2,
    "company": "Cop-A-Mate Products Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Qld",
    "domain": "copamate.com",
    "email": "sales@copamate.com",
    "contactName": "Jo",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-07-30",
    "followupDue": "2026-08-07",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "blank About page.",
    "hookVerified": "2026-07-30",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": "No email written: the fault is late-July research and may not be quoted without re-verification.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "No email written: the fault is late-July research and may not be quoted without re-verification.\n\nHook (research late July, NOT re-verified): blank About page. First company contacted in the campaign. LinkedIn connect completed same day. The original email was fault-leading, which was the right instinct and was then abandoned for eight days."
  },
  {
    "rank": 16,
    "tier": 2,
    "company": "NH Micro Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "NSW",
    "domain": "nhmicro.com",
    "email": "mail@nhmicro.com",
    "contactName": "Josh Hacko",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": "2026-07-30",
    "followupDue": "2026-08-07",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "\"out of date website\".",
    "hookVerified": "2026-07-30",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": "No email written: the fault is late-July research and may not be quoted without re-verification.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "No email written: the fault is late-July research and may not be quoted without re-verification.\n\nfollow-up due 7 to 9 Aug — due today Hook (research late July, NOT re-verified): \"out of date website\". LinkedIn connect completed same day. Josh Hacko confirmed still at NH Micro. The original email used the no-criticism shape at Kyle's explicit request."
  },
  {
    "rank": 17,
    "tier": 2,
    "company": "Decem Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "WA",
    "domain": "decem.com.au",
    "email": "admin@decem.com.au",
    "contactName": "Chris Clarke",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-12T11:24:00+10:00",
    "sendImmediately": false,
    "hook": "typing decem.com.au without https serves the entire site over an unencrypted connection with no redirect.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "decem.com.au serves over an unencrypted connection",
    "emailBody": "Hi Chris,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ndefence suppliers.\n\nIf someone types decem.com.au into a browser without the https in front, your\nserver hands back the entire site over an unencrypted connection and never\nredirects them to the secure one. The secure version exists and its certificate\nis perfectly valid. The redirect is simply not configured. For a business\nworking on defence projects that is an odd look, and it is a one line fix at\nthe server.\n\nThe homepage is also about 3.5 megabytes, most of that four large photographs,\nwhich is slow going on a phone.\n\nWebsites are what I do. Happy to talk if useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): typing decem.com.au without https serves the entire site over an unencrypted connection with no redirect. http://decem.com.au/ returns 200 with a full 31,401-byte HTML page and no Location header. HTTPS exists and its certificate is valid. The redirect is simply not configured. An HSTS header exists on HTTPS responses but cannot protect a first-time visitor arriving over HTTP. Hand-built static site on nginx, no CMS. Copyright ©2026 current. Defence x8. No dated content. No PDFs, no capability statement. Nobody named. Homepage 3.5 MB, mostly four large photographs. Veteran-owned, 18 staff, founded 2019."
  },
  {
    "rank": 18,
    "tier": 3,
    "company": "Windows West Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "WA",
    "domain": "windowswest.com.au",
    "email": "sales@windowswest.com.au",
    "contactName": "May Keven",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-11T11:38:00+10:00",
    "sendImmediately": false,
    "hook": "the only downloadable document is a quad chart, and the word",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your quad chart is on the site but the word defence is not",
    "emailBody": "Hi May,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\nsuppliers into defence programs.\n\nThe only document you offer for download is a quad chart, linked in your\nnavigation as \"Capabilities: Quad Chart\". A quad chart exists for exactly one\naudience. Yet the word defence does not appear anywhere on your website, across\nany of the nine pages.\n\nThe homepage also runs to under 250 words of text, which is thin for a business\nthat has been going since 1994 and whose name sits in a current public industry\ncapability plan on the Defence website.\n\nWebsites are what I do. If tightening this up is on the list, I am happy to talk.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): the only downloadable document is a quad chart, and the word defence appears nowhere on the site across all nine pages. Homepage carries roughly 1,594 characters, thinnest checked. Family-owned since 1994. Copyright © 2026 current. Nobody named (\"approximately 15-20 local people\"). WordPress 7.0.3 with Elementor behind Cloudflare, built by Site Manage. Quad Chart PDF Last-Modified 1 December 2024. No claim is made about the quad chart's contents — its text could not be reliably extracted. Do not let a rewrite invent one."
  },
  {
    "rank": 19,
    "tier": 3,
    "company": "BVE Pty Ltd (Balvibe)",
    "channel": "AIC",
    "stage": "queued",
    "state": "NSW",
    "domain": "balvibe.com.au",
    "email": "orders@balvibe.com.au",
    "contactName": "Don Bailey",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-12T14:41:00+10:00",
    "sendImmediately": false,
    "hook": "homepage heading reads \"What's new!\" and nothing on the site carries a date.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your \"What's new\" section has no dates on it",
    "emailBody": "Hi Don,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\nsuppliers into defence programs.\n\nYour homepage has a heading that reads \"What's new!\", and nothing anywhere on\nthe site carries a date. The newest product mentioned goes back to 2023 and the\nmost recent image was uploaded in August of that year. There is no copyright\nyear in the footer either.\n\nTaken together, a visitor has no way to tell whether the business is busy or\ndormant. Your name sits in a current public industry capability plan on the\nDefence website, so dormant is plainly the wrong answer.\n\nWebsites are what I do. If a refresh is on the list this year I am happy to\ntalk, and if not that is fine.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): homepage heading reads \"What's new!\" and nothing on the site carries a date. No ©, &copy; or the word copyright anywhere across homepage, company and contact pages. Newest product reference 2023; newest image path /uploads/2023/08/. WordPress 7.0.2 with LiteSpeed, actively cached — the site is maintained, it is simply never dated. Defence x0 across five pages. Family-run, exports to NZ and PNG. Peter Bailey (Technical Support) also named. Only PDF is a Terms of Trade document."
  },
  {
    "rank": 20,
    "tier": 3,
    "company": "Puzzle Precision Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "NSW",
    "domain": "puzzleprecision.com.au",
    "email": "puzzle@puzzleprecision.com.au",
    "contactName": "Craig Coburn",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-13T09:18:00+10:00",
    "sendImmediately": false,
    "hook": "nothing on the site can be downloaded.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Nothing on your site can be downloaded",
    "emailBody": "Hi Craig,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\nelectronics and precision manufacturers.\n\nYour site says Puzzle Precision is at the forefront of electronic assembly with\na strong focus on the critical reliability and defence markets. There is nothing\non the site a buyer can download to take that upstairs. No capability statement,\nno datasheet, nothing. The only file you offer is a set of GPG public keys.\n\nNo page carries a date either, and the footer copyright has the symbol but no\nyear after it, so there is no signal anywhere that the site is current.\n\nWebsites and capability material are what I do. Happy to talk if useful, and no\ntrouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): nothing on the site can be downloaded. Zero PDFs across all four pages. No capability statement, no datasheet. The only file offered is a set of GPG public keys. Footer reads © Puzzle Precision Pty Ltd ABN 84 166 982 912 — symbol present, no year. No dated content anywhere. Ten staff, Cardiff NSW. Tempering: Next.js on nginx, the most modern stack in the pipeline. Someone competent built this recently, which lowers the odds they are shopping. Three pages exist in the sitemap but not in the navigation."
  },
  {
    "rank": 21,
    "tier": 3,
    "company": "Currawong Engineering Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Tas",
    "domain": "currawong.aero",
    "email": "admin@currawong.aero",
    "contactName": "Gavin Brett",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-03",
    "followupDue": "2026-08-11",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": ""
  },
  {
    "rank": 22,
    "tier": 3,
    "company": "Ron Allum Deepsea Services Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "NSW",
    "domain": "ronallum.com",
    "email": "enquiries@ronallum.com",
    "contactName": "Ron Allum",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": "2026-08-03",
    "followupDue": "2026-08-11",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": ""
  },
  {
    "rank": 23,
    "tier": 3,
    "company": "KBE Pty Ltd (t/a Summers Engineering)",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "SA",
    "domain": "summersengineering.com.au",
    "email": "sales@summersengineering.com.au",
    "contactName": "James Tononcelli",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-03",
    "followupDue": "2026-08-11",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": ""
  },
  {
    "rank": 24,
    "tier": 3,
    "company": "Rivierra Pty Ltd (t/a Australian General Engineering)",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Vic",
    "domain": "austgen.com.au",
    "email": "sales@austgen.com.au",
    "contactName": "Con Litsios",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-04",
    "followupDue": "2026-08-12",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": ""
  },
  {
    "rank": 25,
    "tier": 3,
    "company": "Value Heat Treatment Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "Vic",
    "domain": "valueheattreatment.com.au",
    "email": "info@valueheattreatment.com.au",
    "contactName": "Raj Kumar",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-07",
    "followupDue": "2026-08-15",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": ""
  },
  {
    "rank": 26,
    "tier": 3,
    "company": "Micca Holdings Pty Ltd (t/a Micks Ally Fab)",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "NT",
    "domain": "mafnt.com.au",
    "email": "admin@mafnt.com.au",
    "contactName": "Mick Carey",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-07-31",
    "followupDue": "2026-08-08",
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "",
    "hookVerified": "2026-07-31",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": "NO LinkedIn presence. Email only. Do not attempt a connect request.",
    "notes": ""
  },
  {
    "rank": 27,
    "tier": 3,
    "company": "Protonautics Pty Ltd",
    "channel": "DIDG",
    "stage": "contacted",
    "state": "NSW",
    "domain": "protonautics.com",
    "email": "info@protonautics.com",
    "contactName": "Ed Bub",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": "2026-08-05",
    "followupDue": "2026-08-13",
    "scheduledSendAt": "2026-08-13T10:34:00+10:00",
    "sendImmediately": false,
    "hook": "copyright is current at 2026, but nothing on the site carries a date, there is no capability statement, and no employee is named anywhere.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Nothing on your site carries a date",
    "emailBody": "Hi Ed,\n\nKyle Hartwell here. I wrote earlier this week about capability material. One\nthing worth flagging since then.\n\nYour copyright is current at 2026, so the site is clearly being maintained. But\nnothing on it carries a date, there is no capability statement a buyer can\ndownload, and nobody from the company is named anywhere. A visitor has no way to\nwork out whether they are looking at a business of three people or thirty, or\nwhether anything on the page happened this year or five years ago.\n\nWebsites are what I do. Happy to talk if useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): copyright is current at 2026, but nothing on the site carries a date, there is no capability statement, and no employee is named anywhere."
  },
  {
    "rank": 28,
    "tier": 3,
    "company": "Teklada Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "Vic",
    "domain": "teklada.com",
    "email": "support@teklada.com",
    "contactName": "Parth Paradkar",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-14T13:16:00+10:00",
    "sendImmediately": false,
    "hook": "newest blog post dated 25 November 2024.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "Your blog's newest post is dated November 2024",
    "emailBody": "Hi Parth,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ntechnology firms.\n\nThe newest post on your blog is dated 25 November 2024, and every other post on\nthat page falls between September and November of the same year. Your case\nstudies page has much more recent work on it, so the blog is the only part of\nthe site telling visitors you went quiet twenty months ago.\n\nI also noticed the word defence does not appear anywhere on the site, though\nyour name sits in a current public industry capability plan on the Defence\nwebsite.\n\nWebsites are what I do. Happy to talk if it is useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07): newest blog post dated 25 November 2024. Confirmed on /blog/; every other post there falls between September and November 2024. Their case studies page carries a 27 January 2026 item, so the site is maintained and the blog specifically is not — twenty months silent. Copyright 2026 current. Defence x0. No PDFs anywhere. Juan du Toit is the other co-founder. Why tier 3 despite a clean fault. WordPress with Elementor built by Geolix, plus HubSpot tracking and Yoast. They have an agency and a marketing stack, so they know and have chosen other priorities."
  },
  {
    "rank": 29,
    "tier": 3,
    "company": "SecureWare Pty Ltd",
    "channel": "AIC",
    "stage": "queued",
    "state": "SA",
    "domain": "secureware.com.au",
    "email": "info@secureware.com.au",
    "contactName": "Adam Barker",
    "nameVerified": "directory",
    "fallbackGreeting": "Good morning,",
    "sentDate": null,
    "followupDue": null,
    "scheduledSendAt": "2026-08-17T09:41:00+10:00",
    "sendImmediately": false,
    "hook": "the homepage block headed \"Latest News Updates\" has as its newest item 13 July 2023.",
    "hookVerified": "2026-08-07",
    "emailStatus": "ready",
    "emailSubject": "The newest item under Latest News Updates is from 2023",
    "emailBody": "Hi Adam,\n\nKyle Hartwell here. I run Ironpeak Consulting and work with Australian\ntechnology and security firms.\n\nYour homepage carries a block headed \"Latest News Updates\". The newest item in\nit is dated 13 July 2023, and the two behind that are from 2019. You chose that\nblock to show visitors the business is moving, and at the moment it does the\nopposite.\n\nThe other thing I noticed is that nobody from Secureware is named on the site.\nFive of your clients have put their names to testimonials, SA Power Networks and\nREDARC among them, and none of your own people appear anywhere.\n\nWebsites are what I do. Happy to talk if useful, and no trouble if not.",
    "emailBlocker": null,
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": null,
    "notes": "Hook (verified 2026-08-07 in a real browser): the homepage block headed \"Latest News Updates\" has as its newest item 13 July 2023. This site sits behind an Imperva WAF that blocks scripted access, so it was opened manually rather than inferred. /news/ shows \"ANNOUNCEMENT | JUL 13, 2023 — Secureware's 4th appearance in the CRN Fast50\" as newest; the two behind it are from 2019. /contact/ publishes info@secureware.com.au with 311 Portrush Road, Norwood SA 5067. Copyright © 2026 current. Zero defence-sector mentions; the single \"defence\" string is \"defences\" in the cyber sense. One PDF sitewide, a terms document. A /capabilities/ page exists offering no downloadable capability statement. On the name: two testimonials on their own site refer to \"Adam and his team\" and \"dealing with Adam over the last 15 or so years\", corroborating an Adam in a senior client-facing role. Reasonably safe. Still worth ten seconds on LinkedIn. Why tier 3: Imperva WAF, an agency (Argon), and a client list of that quality mean budget and an incumbent provider."
  },
  {
    "rank": 30,
    "tier": 3,
    "company": "Luminact Pty Ltd",
    "channel": "DIDG",
    "stage": "linkedin_only",
    "state": "Vic",
    "domain": "luminact.com.au",
    "email": "andrew.skinner@luminact.com.au",
    "contactName": "Andrew Skinner",
    "nameVerified": "own-site",
    "fallbackGreeting": null,
    "sentDate": "2026-08-05",
    "followupDue": null,
    "scheduledSendAt": null,
    "sendImmediately": false,
    "hook": "their homepage invites visitors to \"Take a look at our: White papers\" and that link returns a 404, while their actual white papers are live at two other addresses on the same site.",
    "hookVerified": "2026-08-07",
    "emailStatus": "not-written",
    "emailSubject": null,
    "emailBody": null,
    "emailBlocker": "No email. This record is LinkedIn only.",
    "emailSourceNote": "published on the company's own website, checked 7 August 2026",
    "hardWarning": "LinkedIn only, by Kyle's instruction. No further email to this company.",
    "notes": "No email. This record is LinkedIn only.\n\nHook (verified 2026-08-07, for the LinkedIn note only): their homepage invites visitors to \"Take a look at our: White papers\" and that link returns a 404, while their actual white papers are live at two other addresses on the same site. Also verified: /contact-us/ returns 404 and is orphaned — not linked from anywhere on their own site, so it only harms people arriving from old links or search results. A navigation item labelled \"Land Forces 2024\" appears on every page and opens a page still reading \"Land Forces 24 is shaping up to be even better!\" in future tense, roughly 23 months after the event. Premise correction on file: an earlier note claimed Luminact publishes no email address. That was wrong — they publish four, including three named directors. Never use \"you have no email on your site\" with this company. Freshest site in the pipeline (newest content 17 December 2025, an NZ MoD appointment), most substantive copy, three directors named, two offices. The most sophisticated company on the list, which is why email is closed and LinkedIn stays open."
  }
];
