/**
 * The Ironpeak pipeline master, as researched and narrowed on 31 July 2026.
 *
 * This supersedes the raw grant-recipient import. Same 59 companies, but each
 * now carries a qualification decision, and where one survived it, a named
 * contact with the address published on their own site.
 *
 * 34 are marked skip: listed, foreign-owned, well resourced, or otherwise
 * outside the filter. They stay in the record rather than being deleted,
 * because knowing a company was considered and ruled out, and why, is what
 * stops it being researched again in three months.
 *
 * NOTE: this file carries no email_source_url. The CSV does not record one, and
 * that field is the evidence inferred consent rests on, so it is left empty for
 * Kyle to fill from his own screenshots rather than guessed from the domain. A
 * fabricated source URL would be worse than none.
 */

export interface PipelineRow {
  company: string;
  state: string;
  tier: string;
  grant_total_aud: number;
  streams: string[];
  new_capability: boolean;
  /** Kyle's own vocabulary: skip | watch | queued | advance-queued | contacted */
  status: string;
  status_date: string;
  domain: string;
  published_email: string;
  contact_name: string;
  contact_title: string;
  research_file: string;
  next_action: string;
  headline_purpose: string;
}

export const PIPELINE_MASTER: PipelineRow[] = [
  {
    company: "KBE Pty Ltd",
    state: "NSW",
    tier: "A",
    grant_total_aud: 1250000,
    streams: ["Exports", "Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "summersengineering.com.au",
    published_email: "sales@summersengineering.com.au",
    contact_name: "James Tononcelli",
    contact_title: "Managing Director",
    research_file: "target-15-summers-kbe.md",
    next_action: "t/a Summers Engineering; Ghost Shark components tie",
    headline_purpose: "acquire a 5-axis CNC machine to upscale component manufacture for the Ghost Shark platform",
  },
  {
    company: "Cop-A-Mate Products Pty Ltd",
    state: "Vic",
    tier: "A",
    grant_total_aud: 1089278,
    streams: ["Security", "Sovereign Industrial Priorities"],
    new_capability: true,
    status: "contacted",
    status_date: "2026-07-30",
    domain: "copamate.com",
    published_email: "sales@copamate.com",
    contact_name: "Jo (role unconfirmed)",
    contact_title: "",
    research_file: "target-01-copamate.md",
    next_action: "email 2 due 7-10 Aug",
    headline_purpose: "procure capital equipment to establish local manufacturing capability for mission-critical land-vehicle armour and exhaust components and supporting continuous land-vehicle production and sustainment priorities",
  },
  {
    company: "NH Micro Pty Ltd",
    state: "NSW",
    tier: "A",
    grant_total_aud: 1059779,
    streams: ["Exports", "Sovereign Industrial Priorities"],
    new_capability: true,
    status: "contacted",
    status_date: "2026-07-30",
    domain: "www.nhmicro.com",
    published_email: "mail@nhmicro.com",
    contact_name: "Josh Hacko",
    contact_title: "Technical Director",
    research_file: "target-02-nhmicro.md",
    next_action: "email 2 due 7-10 Aug",
    headline_purpose: "procure an advanced 5-axis ultra-precision machining platform to establish a scalable ultra-precision manufacturing environment to enable domestic production of mission-critical ballscrew components for control actuation systems used in guided weapons platforms",
  },
  {
    company: "SouthernLaunch.Space Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 1035600,
    streams: ["Security", "Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "southernlaunch.space",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "25M Series A June 2026, active newsroom",
    headline_purpose: "acquire range safety equipment, including communication equipment and range network equipment to support test and evaluation activities",
  },
  {
    company: "Aurora Labs Ltd",
    state: "WA",
    tier: "A",
    grant_total_aud: 1000000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "auroralabs3d.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "ASX-listed (A3D)",
    headline_purpose: "acquire an advanced laser powder bed fusion machine for the manufacture of propulsion systems in support of multiple capability domains",
  },
  {
    company: "Ferra Engineering Pty Ltd",
    state: "Qld",
    tier: "A",
    grant_total_aud: 1000000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "US PE group (Accurus/Liberty Hall), ~200 staff",
    headline_purpose: "acquire a 5-axis computer numerical control (CNC) horizontal machining capability to support manufacturing supply into multiple guided weapons and explosive ordnance systems",
  },
  {
    company: "Lintek Pty. Limited",
    state: "NSW",
    tier: "A",
    grant_total_aud: 1000000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "lintek.com.au",
    published_email: "sales@lintek.com.au",
    contact_name: "Renato Morosin",
    contact_title: "Technical Sales (own site)",
    research_file: "target-16-lintek.md",
    next_action: "verify headcount under 50 first",
    headline_purpose: "acquire a tack bonder, lamination press, deburrer and CNC router to upgrade printed circuit board production facility in support of multiple capability domains",
  },
  {
    company: "Micron Manufacturing Pty. Ltd",
    state: "NSW",
    tier: "A",
    grant_total_aud: 1000000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "micronmanufacturing.com.au",
    published_email: "info@micron.com.au",
    contact_name: "Edward McMillan",
    contact_title: "Director and Engineering Manager",
    research_file: "target-17-micron.md",
    next_action: "email domain differs from site domain, as printed",
    headline_purpose: "acquire a machining centre, tooling and associated software for the machining of advanced underwater vehicle super-structures",
  },
  {
    company: "Rivierra Pty Ltd",
    state: "Vic",
    tier: "A",
    grant_total_aud: 1000000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "austgen.com.au",
    published_email: "sales@austgen.com.au",
    contact_name: "Con Litsios",
    contact_title: "Managing Director",
    research_file: "target-20-rivierra-age.md",
    next_action: "t/a Australian General Engineering; confirm AU headcount under 50",
    headline_purpose: "acquire a fully integrated coating line to internalise the powder coating and wet painting of key components manufactured for land systems",
  },
  {
    company: "Prism Defence Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 935186,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "prismdefence.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "no published email anywhere; phone-only contact culture",
    headline_purpose: "procure an excavator to establish a ship motion emulation facility for the test and evaluation of uncrewed aerial systems intended to operate from ships",
  },
  {
    company: "NDE Solutions Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 916052,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "ndesolutions.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "about 65 staff, fresh agency site, external CEO",
    headline_purpose: "acquire non-destructive testing equipment to expand local capability in support of continuous naval shipbuilding and sustainment.",
  },
  {
    company: "Century Engineering Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 901557,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "cenman.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "120+ staff, dedicated defence BD manager",
    headline_purpose: "procure a large-format CNC milling machine for high-precision machining of complex and oversized components within the stringent tolerances and material requirements associated with defence-grade components for naval and land platforms",
  },
  {
    company: "Tynbell Sheetmetal Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 871173,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "tynbellsheetmetal.com.au",
    published_email: "sales@tynbell.com.au",
    contact_name: "Raymond Fenech",
    contact_title: "Owner",
    research_file: "target-18-tynbell.md",
    next_action: "Shape A email: expired SSL is the give",
    headline_purpose: "acquire an upgraded laser cutting system to strengthen manufacturing capability in the naval and land domains",
  },
  {
    company: "Kennewell Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 747754,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "kennewell.com",
    published_email: "quotes@kennewell.com",
    contact_name: "Brett Kennewell",
    contact_title: "Director",
    research_file: "target-19-kennewell.md",
    next_action: "check if Brett self-posted the grant on LinkedIn",
    headline_purpose: "acquire a 5-axis machining centre, vertical lift storage unit and associated equipment for manufacturing supply into infantry fighting vehicle platforms",
  },
  {
    company: "Able Industries Engineering Pty Ltd",
    state: "Vic",
    tier: "A",
    grant_total_aud: 715855,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-04",
    domain: "ableind.com.au",
    published_email: "enquiries@ableind.com.au",
    contact_name: "Stephen Martyn",
    contact_title: "Managing Director",
    research_file: "target-11-ableindustries.md",
    next_action: "send Tue 4 Aug",
    headline_purpose: "acquire robotic welding equipment, coordinate measuring machine, CNC router and power supply upgrades to enhance manufacturing capacity for land combat vehicle and continuous naval shipbuilding and sustainment programs",
  },
  {
    company: "Verseng Group Pty Ltd",
    state: "SA",
    tier: "A",
    grant_total_aud: 651187,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "watch",
    status_date: "2026-07-31",
    domain: "verseng.com.au (auth-gated)",
    published_email: "NONE (site 503)",
    contact_name: "Tim Lillie",
    contact_title: "Managing Director",
    research_file: "",
    next_action: "re-check site in 2-3 weeks; possible rebuild underway; defence BD role exists",
    headline_purpose: "procure robotic welding and autonomous grinding equipment to improve finishing quality and safety in the local production of defence Ground Support Equipment used in sustainment activities, including aircraft sustainment and shipbuilding programs",
  },
  {
    company: "Gurit Australia Pty Limited",
    state: "Qld",
    tier: "A",
    grant_total_aud: 559852,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "gurit.com/australia",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "SIX-listed Swiss multinational subsidiary, active group marketing",
    headline_purpose: "establish local manufacturing capability for bespoke subsea buoyancy for the Ghost Shark autonomous underwater vehicle",
  },
  {
    company: "B. B. Engineering Pty Ltd",
    state: "Vic",
    tier: "A",
    grant_total_aud: 551390,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-10",
    domain: "bbengineering.com.au",
    published_email: "sales@bbengineering.com.au",
    contact_name: "Gary Busuttil",
    contact_title: "Managing Director",
    research_file: "target-10-bbengineering.md",
    next_action: "send Mon 10 Aug",
    headline_purpose: "acquire a 5-axis CNC machine to enhance component manufacture in support of continuous naval shipbuilding and sustainment programs",
  },
  {
    company: "Wessand Pty Ltd",
    state: "Vic",
    tier: "A",
    grant_total_aud: 411189,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-05",
    domain: "www.apparelindustries.com.au",
    published_email: "info@apparelindustries.com.au",
    contact_name: "Christopher Nguyen",
    contact_title: "Director",
    research_file: "target-08-wessand.md",
    next_action: "send Wed 5 Aug",
    headline_purpose: "acquire automated garment manufacturing equipment to strengthen domestic combat uniform manufacture",
  },
  {
    company: "Land Air Sea Space Pty Ltd",
    state: "NSW",
    tier: "B",
    grant_total_aud: 382000,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "watch",
    status_date: "2026-07-31",
    domain: "lass.au (broken TLS)",
    published_email: "NONE FOUND",
    contact_name: "Graham Rainbird",
    contact_title: "Eng and Sales Manager",
    research_file: "",
    next_action: "manual browser check of lass.au/contact-us may surface an email",
    headline_purpose: "procure and integrate an automated inventory management system to enhance efficiency and scalability, ensuring timely delivery of cable assemblies for land, naval and guided weapons programs",
  },
  {
    company: "Dent Engineering Pty Ltd",
    state: "SA",
    tier: "B",
    grant_total_aud: 344722,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "dentengineering.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "no published email (form only); otherwise ideal profile",
    headline_purpose: "acquire a CNC machining centre and lathe for the manufacture of precision components for uncrewed aerial system platforms",
  },
  {
    company: "Protonautics Pty Ltd",
    state: "Qld",
    tier: "B",
    grant_total_aud: 323877,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "protonautics.com",
    published_email: "info@protonautics.com",
    contact_name: "Ed Bub",
    contact_title: "CEO (verify vs Christopher Bush MD)",
    research_file: "target-12-protonautics.md",
    next_action: "resolve Bub/Bush on LinkedIn before send",
    headline_purpose: "acquire a high-capacity horizontal CNC machine to support the manufacture of precision components for the Redback Infantry Fighting Vehicles.",
  },
  {
    company: "Value Heat Treatment Pty Ltd",
    state: "Vic",
    tier: "B",
    grant_total_aud: 271262,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-07",
    domain: "valueheattreatment.com.au",
    published_email: "info@valueheattreatment.com.au",
    contact_name: "Raj Kumar",
    contact_title: "Director",
    research_file: "target-09-valueheat.md",
    next_action: "send Fri 7 Aug",
    headline_purpose: "purchase capital equipment to uplift the heat treatment capability for defence components across land, sea, and air platforms",
  },
  {
    company: "Prestige Precision Tools Pty Ltd",
    state: "Qld",
    tier: "B",
    grant_total_aud: 250000,
    streams: ["Exports"],
    new_capability: true,
    status: "skip",
    status_date: "",
    domain: "pptools.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "target-04-prestige-precision-SKIP.md",
    next_action: "RJS Tech Group, active marketing; watch for warm path to Ron Smyth",
    headline_purpose: "establish the manufacturing capability of high-performance carbide tools, delivering tooling solutions that meet the stringent requirements of platforms such as the Joint Strike Fighter and other advanced weapons systems",
  },
  {
    company: "Skyborne Technologies Pty Ltd",
    state: "Qld",
    tier: "B",
    grant_total_aud: 250000,
    streams: ["Exports"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "skybornetech.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "VC-backed, active PR cadence",
    headline_purpose: "procure a CNC lathe and two automated electronic and avionics testing systems to support the development and integration of autonomous systems",
  },
  {
    company: "Specialised Solutions Pty Ltd",
    state: "SA",
    tier: "B",
    grant_total_aud: 243450,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "specsolutions.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "about 128 staff",
    headline_purpose: "acquire a robotic welding cell and a 10-tonne overhead crane to manufacture high-precision welded components for small and larger modular assemblies used in naval, land and autonomous systems",
  },
  {
    company: "Process Rubber & Plastics Pty. Ltd",
    state: "SA",
    tier: "B",
    grant_total_aud: 215829,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "prp.company",
    published_email: "luke@prp.company",
    contact_name: "Luke Sernecki",
    contact_title: "CEO",
    research_file: "target-14-prp.md",
    next_action: "email from their own quad chart PDF; NEVER reference the founder",
    headline_purpose: "acquire a 5-axis machining centre to increase manufacturing capability for multiple capability domains",
  },
  {
    company: "Coastal Aviation Pty Ltd",
    state: "Qld",
    tier: "B",
    grant_total_aud: 198605,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "coastalaviation.com.au",
    published_email: "info@coastalaviation.com.au",
    contact_name: "Robert Stowe",
    contact_title: "Owner Director",
    research_file: "target-13-coastalaviation.md",
    next_action: "family MRO, Part 145, zero defence on site",
    headline_purpose: "acquire a 5-axis CNC milling machine and fabrication equipment to enhance manufacturing of large defence components for air and guided-weapons platforms",
  },
  {
    company: "Jehbco Manufacturing Pty Ltd",
    state: "NSW",
    tier: "B",
    grant_total_aud: 192264,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "jehbco.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "active SEO article program, posts 11 days old",
    headline_purpose: "purchase a silicone rubber extruder to increase production capacity, improve dimensional accuracy, and enable the manufacture of high-performance silicone profiles for defence sealing and insulation applications across multiple platforms",
  },
  {
    company: "Rosebank Engineering Pty Ltd",
    state: "Vic",
    tier: "B",
    grant_total_aud: 185897,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-06",
    domain: "rosebankeng.com.au",
    published_email: "info@rosebankeng.com.au",
    contact_name: "Aidan Butler-Bonnice",
    contact_title: "General Manager",
    research_file: "target-07-rosebank.md",
    next_action: "send Thu 6 Aug; ASDAM-owned, tempered expectations",
    headline_purpose: "procure and integrate a purpose-built cold spray facility with advanced robotic control to support the manufacture of the landing gear for the MQ-28 Ghost Bat",
  },
  {
    company: "Currawong Engineering Pty Ltd",
    state: "Tas",
    tier: "B",
    grant_total_aud: 184659,
    streams: ["Exports"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "currawongeng.com",
    published_email: "admin@currawong.aero",
    contact_name: "Gavin Brett",
    contact_title: "Founder and CEO",
    research_file: "target-22-currawong.md",
    next_action: "PRIORITY: Land Forces timing; send early, verify show edition",
    headline_purpose: "procure a vertical machining centre to enhance the manufacture of aerospace-grade electronic speed controllers and engines to support the growing demand from export supply chains",
  },
  {
    company: "Luminact Pty Ltd",
    state: "Vic",
    tier: "B",
    grant_total_aud: 142818,
    streams: ["Exports"],
    new_capability: true,
    status: "advance-queued",
    status_date: "2026-07-31",
    domain: "luminact.com.au",
    published_email: "andrew.skinner@luminact.com.au",
    contact_name: "Andrew Skinner",
    contact_title: "Director, Co-Founder",
    research_file: "target-21-luminact.md",
    next_action: "email is VDSN-published; Kyle to approve consent basis or go LinkedIn-first",
    headline_purpose: "acquire equipment and commission a transportable Command, Control, Communications, and Computers (C4) Systems Integration Lab to integrate and verify communications, networking, and battlespace management systems, to support repeatable testing and evaluation for land platforms",
  },
  {
    company: "Micca Holdings Pty Ltd",
    state: "NT",
    tier: "B",
    grant_total_aud: 112419,
    streams: ["Skilling", "Sovereign Industrial Priorities"],
    new_capability: true,
    status: "contacted",
    status_date: "2026-07-31",
    domain: "micksallyfab.com.au",
    published_email: "admin@mafnt.com.au",
    contact_name: "Mick Carey",
    contact_title: "Managing Director",
    research_file: "target-03-micca-micksallyfab.md",
    next_action: "email 2 due 8-10 Aug; no LinkedIn presence, email-only thread",
    headline_purpose: "acquire a rotary fibre laser cutting machine and a laser welding machine to uplift naval sustainment capability in Northern Australia.",
  },
  {
    company: "Stahl Metall Pty Ltd",
    state: "Vic",
    tier: "B",
    grant_total_aud: 112272,
    streams: ["Exports"],
    new_capability: true,
    status: "watch",
    status_date: "2026-07-31",
    domain: "stahlmetall.com",
    published_email: "Sales@StahlMetall.Com",
    contact_name: "Anton Fonseka",
    contact_title: "Director of BD",
    research_file: "",
    next_action: "active self-marketer, low gap; revisit if their comms go quiet",
    headline_purpose: "procure automated machinery and quality control equipment to support export opportunities establishing automated wire processing for high performance electrical assemblies used within multiple defence platforms",
  },
  {
    company: "Rheon Systems Pty Ltd",
    state: "Qld",
    tier: "C",
    grant_total_aud: 90402,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "rheonsystems.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "self-announced grant on fresh site; no named person findable",
    headline_purpose: "procure capital equipment to establish NATA-accredited pressure testing and calibration capability to support test, evaluation and certification activities of Defence systems",
  },
  {
    company: "Electronic & Electrical Solutions Pty Ltd",
    state: "Qld",
    tier: "C",
    grant_total_aud: 73115,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "eesolutions.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "monthly content marketing, own quad chart; comms handled",
    headline_purpose: "acquire capital equipment to enhance the capacity and quality of manufacturing PCBs used across multiple defence platforms, particularly for guided-weapons production and the sustainment and enhancement of combined-arms land systems",
  },
  {
    company: "Amtech Precision Pty Ltd",
    state: "ACT",
    tier: "C",
    grant_total_aud: 69750,
    streams: ["Sovereign Industrial Priorities"],
    new_capability: true,
    status: "watch",
    status_date: "2026-07-31",
    domain: "amtechprecision.com.au",
    published_email: "phil@amtechprecision.com.au (directory)",
    contact_name: "Phil (surname unknown)",
    contact_title: "Principal",
    research_file: "",
    next_action: "Google Sites near-BUILD; need full name before contact",
    headline_purpose: "acquire a coordinate measuring machine and profile projector to enhance precision machining manufacturing capability in support of multiple capability domains",
  },
  {
    company: "Ron Allum Deepsea Services Pty Ltd",
    state: "NSW",
    tier: "C",
    grant_total_aud: 57634,
    streams: ["Exports", "Skilling"],
    new_capability: true,
    status: "queued",
    status_date: "2026-08-03",
    domain: "ronallum.com",
    published_email: "enquiries@ronallum.com",
    contact_name: "Damian Mackey",
    contact_title: "Operations Manager",
    research_file: "target-06-ronallum.md",
    next_action: "send Mon 3 Aug 9:30, connect ~11:30",
    headline_purpose: "upgrade its subsea test and evaluation system to support safe, repeatable, and production-scale testing of subsea systems; and obtain relevant ISO certification to remove export barriers",
  },
  {
    company: "Arlula Pty Ltd",
    state: "NSW",
    tier: "C",
    grant_total_aud: 56014,
    streams: ["Exports"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "arlula.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "VC-backed incl Lockheed Martin Ventures, active newsroom",
    headline_purpose: "achieve ISO27001, ISO 9001, and general data protection regulation certification to enable the secure handling of satellite data and overcome existing export barriers to access defence markets in US and Europe",
  },
  {
    company: "Blueroom Simulations Pty Ltd",
    state: "Vic",
    tier: "C",
    grant_total_aud: 45800,
    streams: ["Exports"],
    new_capability: true,
    status: "skip",
    status_date: "2026-07-31",
    domain: "blueroomxr.com",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "no published email + content days old + full marketing engine",
    headline_purpose: "upgrade its mixed reality testing laboratory to allow personnel to develop complex skills through immersive and realistic virtual training environments and to leverage export opportunities",
  },
  {
    company: "U-Neek Bending Co. Pty Ltd",
    state: "Vic",
    tier: "C",
    grant_total_aud: 34526,
    streams: ["Exports"],
    new_capability: true,
    status: "watch",
    status_date: "2026-07-31",
    domain: "uneek.com.au",
    published_email: "sales@uneek.com.au",
    contact_name: "Les Sabo",
    contact_title: "Managing Director",
    research_file: "",
    next_action: "NADCAP-gap angle; drops to skip if Mity rebuild is recent",
    headline_purpose: "obtain NADCAP certification and acquire advanced welding equipment to enhance the manufacture of critical welded components to support supply chains across aerospace, land and maritime domains.",
  },
  {
    company: "Thrust Maritime Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 240116,
    streams: ["Skilling"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "upskill its workforce in multiple technical and trade disciplines to ensure compliance with RAN and international standards",
  },
  {
    company: "JFD Australia Pty Ltd",
    state: "WA",
    tier: "D",
    grant_total_aud: 200000,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift governance, physical and cybersecurity posture to meet Defence security requirements",
  },
  {
    company: "PHM Technology Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 100000,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift cybersecurity controls and enhance physical security to meet Defence security requirements",
  },
  {
    company: "Redarc Defence & Space Pty Ltd",
    state: "SA",
    tier: "D",
    grant_total_aud: 100000,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift physical security to meet Defence security requirements",
  },
  {
    company: "HIFraser Pty Ltd",
    state: "NSW",
    tier: "D",
    grant_total_aud: 91294,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift physical security to meet Defence security requirements",
  },
  {
    company: "Lunar Outpost Oceania Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 85990,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "enhance Essential Eight security controls and uplift physical security to meet Defence security requirements",
  },
  {
    company: "Ascent Professional Services Pty Ltd",
    state: "SA",
    tier: "D",
    grant_total_aud: 84419,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "enhance cybersecurity maturity in order to meet Defence Security requirements",
  },
  {
    company: "APV Engineering and Testing Services Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 83746,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift cybersecurity controls to meet Defence security requirements",
  },
  {
    company: "Automation and Process Control Services Pty Ltd",
    state: "SA",
    tier: "D",
    grant_total_aud: 51250,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift cybersecurity controls to meet Defence security requirements",
  },
  {
    company: "Switchmode Power Supplies Pty Ltd",
    state: "NSW",
    tier: "D",
    grant_total_aud: 38864,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift security controls to meet Defence security requirements",
  },
  {
    company: "Bastion Defence Consulting Pty Ltd",
    state: "SA",
    tier: "D",
    grant_total_aud: 34550,
    streams: ["Skilling"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "upskill engineering personnel in model-based architectural design, requirements management, and virtual verification and validation",
  },
  {
    company: "Applied Virtual Simulation Pty Ltd",
    state: "NSW",
    tier: "D",
    grant_total_aud: 32623,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift physical security to meet Defence security requirements",
  },
  {
    company: "AST Oceanics Pty Ltd",
    state: "WA",
    tier: "D",
    grant_total_aud: 28367,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift cybersecurity controls to meet Defence security requirements",
  },
  {
    company: "Mellori Solutions Pty Ltd",
    state: "NSW",
    tier: "D",
    grant_total_aud: 24968,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift physical security to meet Defence security requirements",
  },
  {
    company: "Hargo Engineering Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 20000,
    streams: ["Skilling"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "upskill staff through on-the-job training of apprentices leading to a Certificate III in Engineering - Mechanical Trade",
  },
  {
    company: "Consunet Pty Ltd",
    state: "SA",
    tier: "D",
    grant_total_aud: 16346,
    streams: ["Security"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "uplift cybersecurity controls to meet Defence security requirements.",
  },
  {
    company: "Huber & Suhner (Australia) Pty Ltd",
    state: "NSW",
    tier: "D",
    grant_total_aud: 6572,
    streams: ["Skilling"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "",
    next_action: "auto-skip: tier D, no new capability (qualification-parameters.md stage 0)",
    headline_purpose: "develop staff through on-the-job training in cable and harness manufacturing and inspection",
  },
  {
    company: "SYPAQ Systems Pty Ltd",
    state: "Vic",
    tier: "D",
    grant_total_aud: 6315,
    streams: ["Skilling"],
    new_capability: false,
    status: "skip",
    status_date: "",
    domain: "sypaq.com.au",
    published_email: "",
    contact_name: "",
    contact_title: "",
    research_file: "target-05-sypaq-SKIP.md",
    next_action: "~100+ staff, marketing function; ecosystem not pipeline",
    headline_purpose: "develop workforce capability in electronic warfare",
  }
];
